<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>PK-84 LOC Magnum</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>13</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>1322.6726743018103</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>566.99</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>431.8</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>684.4626111982925</CalcMass>
                    <CalcCG>431.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>533.4</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>139.7</BaseDia>
                    <ShoulderLen>127.0</ShoulderLen>
                    <ShoulderOD>136.525</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>605.1497287582963</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>304.8</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>605.1497287582963</CalcMass>
                    <CalcCG>304.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>609.6</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <OD>140.716</OD>
                    <ID>136.652</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>136.652</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>115.42173362593729</KnownMass>
                            <Density>848.979</Density>
                            <Material>Spiral/Glassine</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>139.7</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>463.55</Xb>
                            <CalcMass>115.42173362593729</CalcMass>
                            <CalcCG>139.7</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>279.4</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <OD>136.652</OD>
                            <ID>134.366</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>857.2954490742557</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>431.8</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>857.2954490742557</CalcMass>
                    <CalcCG>431.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>863.6</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>3</SerialNo>
                    <OD>140.716</OD>
                    <ID>136.652</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>136.652</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>63.79824422499983</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>120.65</Xb>
                            <CalcMass>63.79824422499983</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>136.652</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>21.2621</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Hdwr</Name>
                            <KnownCG>130.175</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>130.175</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <BodyTube>
                            <KnownMass>152.39576502612763</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>MMT-54mm</Name>
                            <KnownCG>254.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>152.39576502612763</CalcMass>
                            <CalcCG>254.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>508.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>57.404</OD>
                            <ID>54.356</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>54.356</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>52.54024916538176</KnownMass>
                                    <Density>724.996</Density>
                                    <Material>Aircraft plywood (LOC)</Material>
                                    <Name>Centering ring</Name>
                                    <KnownCG>3.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>15.875</Xb>
                                    <CalcMass>52.54024916538176</CalcMass>
                                    <CalcCG>3.0</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>6.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>7</SerialNo>
                                    <OD>136.652</OD>
                                    <ID>57.404</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <CustomFinSet>
                            <KnownMass>583.875237858479</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Custom Fin set</Name>
                            <KnownCG>159.77851749962818</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>584.2</Xb>
                            <CalcMass>583.875237858479</CalcMass>
                            <CalcCG>159.77851749962818</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>8</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>6.0</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>266.69999999999993</TabLength>
                            <TabDepth>41.656</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>266.69999999999993,0.0|288.925,136.525|158.75,184.15|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Ring>
                            <KnownMass>52.54024916538176</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>857.25</Xb>
                            <CalcMass>52.54024916538176</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>136.652</OD>
                            <ID>57.404</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>52.54024916538176</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>279.4</Xb>
                            <CalcMass>52.54024916538176</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>136.652</OD>
                            <ID>57.404</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>155.922</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>SCM-4 with Y-harness</Name>
                            <KnownCG>330.2</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>330.2</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>22.86</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>1224.7016400000002</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>TN-18</Name>
                            <KnownCG>254.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>254.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>60.96</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>142.0</KnownMass>
                            <Density>5.4997469558988534E-8</Density>
                            <Material>Rip stop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>139.7</Xb>
                            <CalcMass>18.6546933988444</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <Dia>1470.0</Dia>
                            <ShroudLineCount>12</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1524.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>