<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>PK-96 MMAS Bruiser EXP-3.00</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>25</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>1732.919294513178</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>907.185</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>342.9</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1005.2474732089967</CalcMass>
                    <CalcCG>342.9</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>558.8</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>194.945</BaseDia>
                    <ShoulderLen>127.0</ShoulderLen>
                    <ShoulderOD>191.77</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>1052.223486703121</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Payload Bay</Name>
                    <KnownCG>381.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1052.223486703121</CalcMass>
                    <CalcCG>381.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>762.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>194.945</OD>
                    <ID>190.881</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>190.881</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>209.786</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>571.5</Xb>
                            <CalcMass>339.23751884456146</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>381.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>190.881</OD>
                            <ID>188.214</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>454.001</KnownMass>
                            <Density>3.514927519270546E-8</Density>
                            <Material>Rip stop nylon</Material>
                            <Name>Parachute 2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>247.65</Xb>
                            <CalcMass>32.8048414065216</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>87.72524999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <Dia>2438.4</Dia>
                            <ShroudLineCount>16</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>2009.9999999999998</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>153.08701920000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>346.075</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>346.075</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>91.44000000000001</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>21.2621</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Hdwr</Name>
                            <KnownCG>136.525</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>136.525</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>21.2621</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Hdwr</Name>
                            <KnownCG>593.725</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>593.725</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>2104.446973406242</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>762.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>2104.446973406242</CalcMass>
                    <CalcCG>762.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1524.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>8</SerialNo>
                    <OD>194.945</OD>
                    <ID>190.881</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>190.881</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>131.74211161338653</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>3.175</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>149.225</Xb>
                            <CalcMass>131.74211161338653</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>190.881</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>605.1497287582968</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>TWT</Name>
                            <KnownCG>304.8</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>6.35</Xb>
                            <CalcMass>605.1497287582968</CalcMass>
                            <CalcCG>304.8</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>609.6</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>140.716</OD>
                            <ID>136.652</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>136.652</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>41.50884230611781</KnownMass>
                                    <Density>724.996</Density>
                                    <Material>Aircraft plywood (LOC)</Material>
                                    <Name>Centering ring</Name>
                                    <KnownCG>3.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>66.675</Xb>
                                    <CalcMass>41.50884230611781</CalcMass>
                                    <CalcCG>3.0</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>6.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>11</SerialNo>
                                    <OD>136.652</OD>
                                    <ID>80.772</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <Ring>
                                    <KnownMass>73.7088</KnownMass>
                                    <Density>1121.29</Density>
                                    <Material>Paper</Material>
                                    <Name>Tube coupler</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>0.0</Xb>
                                    <CalcMass>27.716979764126773</CalcMass>
                                    <CalcCG>0.0</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>50.8</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>12</SerialNo>
                                    <OD>136.652</OD>
                                    <ID>134.366</ID>
                                    <UsageCode>4</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <Ring>
                                    <KnownMass>41.50524487311795</KnownMass>
                                    <Density>724.996</Density>
                                    <Material>Aircraft plywood (LOC)</Material>
                                    <Name>Centering ring</Name>
                                    <KnownCG>2.99974</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>473.075</Xb>
                                    <CalcMass>41.50524487311795</CalcMass>
                                    <CalcCG>2.99974</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>5.99948</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>13</SerialNo>
                                    <OD>136.652</OD>
                                    <ID>80.772</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <BodyTube>
                            <KnownMass>481.60525288370667</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>MMT</Name>
                            <KnownCG>381.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>481.60525288370667</CalcMass>
                            <CalcCG>381.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>762.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <OD>80.772</OD>
                            <ID>76.2</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>76.2</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>85.24706012678502</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring - Top</Name>
                            <KnownCG>4.5</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>958.85</Xb>
                            <CalcMass>85.24706012678502</CalcMass>
                            <CalcCG>4.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>9.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <OD>190.881</OD>
                            <ID>140.716</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <CustomFinSet>
                            <KnownMass>807.7113122749508</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Custom Fin set</Name>
                            <KnownCG>158.74730068453997</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>6.35</Xb>
                            <CalcMass>807.7113122749508</CalcMass>
                            <CalcCG>158.74730068453997</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>16</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>9.0</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>266.7</TabLength>
                            <TabDepth>27.1145</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>266.69999999999993,0.0|266.7,174.625|139.7,174.625|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Ring>
                            <KnownMass>56.831373417856675</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring </Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>1250.95</Xb>
                            <CalcMass>56.831373417856675</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>190.881</OD>
                            <ID>140.716</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>56.831373417856675</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>1498.6</Xb>
                            <CalcMass>56.831373417856675</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>18</SerialNo>
                            <OD>190.881</OD>
                            <ID>140.716</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>21.2621</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Hdwr</Name>
                            <KnownCG>384.175</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>384.175</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>19</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>21.2621</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Hdwr</Name>
                            <KnownCG>161.925</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>161.925</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>20</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>153.08701920000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>346.075</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>346.075</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>91.44000000000001</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>21</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>28.4006</KnownMass>
                            <Density>7.836411110493913E-8</Density>
                            <Material>Rip stop nylon</Material>
                            <Name>Parachute 1</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>422.275</Xb>
                            <CalcMass>6.218231132280961</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>87.72524999999999</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>22</SerialNo>
                            <Dia>710.999</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>762.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>209.786</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>577.85</Xb>
                            <CalcMass>339.23751884456146</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>381.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>23</SerialNo>
                            <OD>190.881</OD>
                            <ID>188.214</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>102.02574554019166</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>1511.3</Xb>
                            <CalcMass>102.02574554019166</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>24</SerialNo>
                            <OD>190.754</OD>
                            <ID>80.772</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>51.0291</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>MMAS</Name>
                            <KnownCG>1524.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>1524.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>25</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>