<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Bullpuppy 2.1</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>9</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>451.511727173543</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>99.223</KnownMass>
                    <Density>946.0</Density>
                    <Material>Polypropylene, bulk</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>190.5</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>108.20987904853966</CalcMass>
                    <CalcCG>190.5</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>241.29999999999998</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.048</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>57.40399999999999</BaseDia>
                    <ShoulderLen>63.5</ShoulderLen>
                    <ShoulderOD>54.102</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>88.0572593643421</KnownMass>
                    <Density>958.70501055</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Airframe</Name>
                    <KnownCG>165.1</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>88.0572593643421</CalcMass>
                    <CalcCG>165.1</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>330.2</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>57.81</OD>
                    <ID>54.661</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>54.661</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Parachute>
                            <KnownMass>24.99364061885334</KnownMass>
                            <Density>0.00589</Density>
                            <Material>Nylon fabric, ripstop, 1.9 oz actual</Material>
                            <Name>Parachute, 24 in., 1.9oz nylon, 8 lines, spill hole</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>185.42</Xb>
                            <CalcMass>24.99364061885334</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>26.014499999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <Dia>609.5999999999999</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>609.5999999999999</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0016</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon Paracord, 110 lb, 1/16 in. dia.</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <FinSet>
                            <KnownMass>4.69537940422805</KnownMass>
                            <Density>1905.23598922</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Fin set</Name>
                            <KnownCG>23.045142526365215</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>3.175</Xb>
                            <CalcMass>4.69537940422805</CalcMass>
                            <CalcCG>23.045142526365215</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>4</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>34.925</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>22.225</SemiSpan>
                            <SweepDistance>34.2104275790956</SweepDistance>
                            <Thickness>1.5875</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <MassObject>
                            <KnownMass>34.80001574400001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>220.98</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>220.98</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>88.41410505659049</KnownMass>
                    <Density>1049.2093265</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Transition</Name>
                    <KnownCG>38.4526989842849</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>88.41410505659049</CalcMass>
                    <CalcCG>38.4526989842849</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>133.35</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>6</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>31.398716111109163</KnownMass>
                            <Density>958.70501055</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>29mm MMT</Name>
                            <KnownCG>107.94999999999999</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-78.74000000000001</Xb>
                            <CalcMass>31.398716111109163</CalcMass>
                            <CalcCG>107.94999999999999</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>215.89999999999998</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>32.233</OD>
                            <ID>29.083</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>29.083</MotorDia>
                            <EngineOverhang>12.7</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <CustomFinSet>
                            <KnownMass>61.33898468482874</KnownMass>
                            <Density>1905.23598922</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Fin set</Name>
                            <KnownCG>57.29800819137722</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>9.525</Xb>
                            <CalcMass>61.33898468482874</CalcMass>
                            <CalcCG>57.29800819137722</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>8</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>1.5875</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>88.89999999999998,-6.873129835600844|88.90401278526299,82.55|60.329012785263,82.55|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Ring>
                            <KnownMass>5.2988177976970325</KnownMass>
                            <Density>724.99563538</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>2.3875</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-48.26</Xb>
                            <CalcMass>5.2988177976970325</CalcMass>
                            <CalcCG>2.3875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>4.775</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>54.661</OD>
                            <ID>32.233</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                    <FrontShoulderLen>44.45</FrontShoulderLen>
                    <RearShoulderLen>0.025</RearShoulderLen>
                    <FrontShoulderDia>54.153</FrontShoulderDia>
                    <RearShoulderDia>28.575</RearShoulderDia>
                    <FrontDia>57.81</FrontDia>
                    <RearDia>32.233</RearDia>
                </Transition>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>