<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>PML Callisto 29mm</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>8</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>700.5640365548655</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>99.223</KnownMass>
                    <Density>1518.1959343033514</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>190.5</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>133.8795081669364</CalcMass>
                    <CalcCG>190.5</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>241.29999999999998</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.3622</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>57.810399999999994</BaseDia>
                    <ShoulderLen>44.45</ShoulderLen>
                    <ShoulderOD>54.6608</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>243.85087208587035</KnownMass>
                    <Density>958.70501055</Density>
                    <Material>Kraft phenolic</Material>
                    <Name>Body tube</Name>
                    <KnownCG>457.2</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>243.85087208587035</CalcMass>
                    <CalcCG>457.2</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>914.4</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <OD>57.81</OD>
                    <ID>54.661</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>54.661</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>67.85933056059623</KnownMass>
                            <Density>1905.23598922</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Fin set</Name>
                            <KnownCG>49.422642809379965</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>806.45</Xb>
                            <CalcMass>67.85933056059623</CalcMass>
                            <CalcCG>49.422642809379965</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>2</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>101.6</RootChord>
                            <TipChord>44.45</TipChord>
                            <SemiSpan>101.6</SemiSpan>
                            <SweepDistance>25.4070784615739</SweepDistance>
                            <Thickness>1.6002</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>44.04868792790956</KnownMass>
                            <Density>952.8</Density>
                            <Material>PML kraft phenolic</Material>
                            <Name>29mm MMT</Name>
                            <KnownCG>152.39999999999998</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>44.04868792790956</CalcMass>
                            <CalcCG>152.39999999999998</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>304.79999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>32.23259999999999</OD>
                            <ID>29.083</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>29.083</MotorDia>
                            <EngineOverhang>12.7</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Parachute>
                            <KnownMass>24.99364061885334</KnownMass>
                            <Density>0.00589</Density>
                            <Material>Nylon fabric, ripstop, 1.9 oz actual</Material>
                            <Name>Parachute, 24 in., 1.9oz nylon, 8 lines, spill hole</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>546.1</Xb>
                            <CalcMass>24.99364061885334</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <Dia>609.5999999999999</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>609.5999999999999</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0016</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon Paracord, 110 lb, 1/16 in. dia.</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>3.353728006947783</KnownMass>
                            <Density>724.99563538</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>2.3875</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>904.875</Xb>
                            <CalcMass>3.353728006947783</CalcMass>
                            <CalcCG>2.3875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>4.775</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>54.661</OD>
                            <ID>41.885</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>3.353728006947783</KnownMass>
                            <Density>724.99563538</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>2.3875</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>635.0</Xb>
                            <CalcMass>3.353728006947783</CalcMass>
                            <CalcCG>2.3875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>4.775</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>54.661</OD>
                            <ID>41.885</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>3.353728006947783</KnownMass>
                            <Density>724.99563538</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>2.3875</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>800.0999999999999</Xb>
                            <CalcMass>3.353728006947783</CalcMass>
                            <CalcCG>2.3875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>4.775</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>54.661</OD>
                            <ID>41.885</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>43.50001968</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>317.5</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>317.5</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>