<RockSimDocument>
<FileVersion>4</FileVersion>
<DesignInformation>
<RocketDesign>
<Name>PK-77 HyperLoc 835 35th Anniversay Edition</Name>
<CalculateCD>1</CalculateCD>
<ProCalculateCD>1</ProCalculateCD>
<ProCalculateCN>1</ProCalculateCN>
<FixedCd>0.75</FixedCd>
<FixedCd2>0.8</FixedCd2>
<FixedCd3>0.81</FixedCd3>
<FixedCd2Alone>0.95</FixedCd2Alone>
<FixedCd3Alone>0.95</FixedCd3Alone>
<StageCount>1</StageCount>
<Stage3Mass>0.</Stage3Mass>
<Stage2Mass>0.</Stage2Mass>
<Stage1Mass>0.</Stage1Mass>
<Stage321CG>0.</Stage321CG>
<Stage32CG>0.</Stage32CG>
<Stage3CG>0.</Stage3CG>
<Stage2CGAlone>0.</Stage2CGAlone>
<Stage1CGAlone>0.</Stage1CGAlone>
<CPCalcFlags>1</CPCalcFlags>
<LaunchGuideLength>914.4</LaunchGuideLength>
<UseKnownMass>0</UseKnownMass>
<DefaultFinish>0</DefaultFinish>
<FinishMedium>0</FinishMedium>
<FinishCoatCount>1</FinishCoatCount>
<GlueType>0</GlueType>
<CPSimFlags>1</CPSimFlags>
<LastSerialNumber>26</LastSerialNumber>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<CameraState>CSV1|1|949.96,38.3885,-1.13687e-13|949.96,38.3885,997.979|0,1,0|712.919,1359.22|30|2|997.979|0|0|0|0|0</CameraState>
<BarromanXN>0,1362.71,0,0</BarromanXN>
<BarrowmanCNa>0,10.0252,0,0</BarrowmanCNa>
<RockSimXN>0,1475.85,0,0</RockSimXN>
<RockSimCNa>0,14.9405,0,0</RockSimCNa>
<RockSimCNa90>0,0,0,0</RockSimCNa90>
<RockSimXN90>0,0,0,0</RockSimXN90>
<ViewType>0</ViewType>
<ViewStageCount>1</ViewStageCount>
<ViewTypeEdit>0</ViewTypeEdit>
<ViewStageCountEdit>1</ViewStageCountEdit>
<ZoomFactor>0.</ZoomFactor>
<ZoomFactorEdit>0.</ZoomFactorEdit>
<ScrollPosX>0</ScrollPosX>
<ScrollPosY>0</ScrollPosY>
<ScrollPosXEdit>0</ScrollPosXEdit>
<ScrollPosYEdit>0</ScrollPosYEdit>
<ThreeDFlags>7</ThreeDFlags>
<ThreeDFlagsEdit>0</ThreeDFlagsEdit>
<UseModelSprite>0</UseModelSprite>
<StaticMarginRef>0</StaticMarginRef>
<UserRefDiameter>0.</UserRefDiameter>
<SideMarkerHeight>9.99998</SideMarkerHeight>
<SideDimensionHeight>9.99998</SideDimensionHeight>
<BaseMarkerHeight>9.99998</BaseMarkerHeight>
<BaseDimensionHeight>9.99998</BaseDimensionHeight>
<ShowGlideCP>0</ShowGlideCP>
<ShowGridTypeSide>0</ShowGridTypeSide>
<ShowGridTypeBase>0</ShowGridTypeBase>
<GridSpacing>10.</GridSpacing>
<GridOpacity>0.15</GridOpacity>
<GridColor>black</GridColor>
<MaxDiaWithFins>321.31</MaxDiaWithFins>
<MaxDiaWithoutFins>101.6</MaxDiaWithoutFins>
<MaxLenWithFins>1849.12</MaxLenWithFins>
<MaxLenWithoutFins>1849.12</MaxLenWithoutFins>
<MinXExtent>0.</MinXExtent>
<MaxXExtent>1849.12</MaxXExtent>
<CalculatedMaxStageDia>0,101.6,0,0</CalculatedMaxStageDia>
<CalculatedStageLen>0,1849.12,0,0</CalculatedStageLen>
<Cd3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd3>
<Cd32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd32>
<Cd321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd321>
<Cb3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb3>
<Cb32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb32>
<Cb321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb321>
<CNa3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa3>
<CNa32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa32>
<CNa321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa321>
<CP3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP3>
<CP32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP32>
<CP321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP321>
<SimulationEventList>
<SimulationEvent>
<PartSerialNo>15</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>24</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</SimulationEventList>
<Stage3Parts>
<NoseCone>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>141.748</KnownMass>
<Density>1049.21</Density>
<Material>Polystyrene PS</Material>
<Name>Nose cone</Name>
<KnownCG>209.55</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>340.106</CalcMass>
<CalcCG>265.224</CalcCG>
<WettedSurface>0.0700863</WettedSurface>
<PaintedSurface>0.0700863</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC PNC-3.90</PartNo>
<PartDesc>Plastic nose cone</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>1</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>2.</BarrowmanCNa>
<BarrowmanXN>0.150518</BarrowmanXN>
<RockSimCNa>2.</RockSimCNa>
<RockSimXN>0.150518</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>0.</Station>
<Len>325.12</Len>
<BaseDia>101.6</BaseDia>
<FinishCode>0</FinishCode>
<ShapeCode>1</ShapeCode>
<ConstructionType>1</ConstructionType>
<ShoulderLen>95.25</ShoulderLen>
<WallThickness>3.175</WallThickness>
<ShapeParameter>0.</ShapeParameter>
<ShoulderOD>98.552</ShoulderOD>
<BaseExtensionLen>0.</BaseExtensionLen>
<CoreDia>0.</CoreDia>
<CoreLen>0.</CoreLen>
<AttachedParts>
</AttachedParts>
</NoseCone>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>171.012</CalcMass>
<CalcCG>190.5</CalcCG>
<WettedSurface>0.12161</WettedSurface>
<PaintedSurface>0.12161</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC BT-3.9</PartNo>
<PartDesc>Airframe tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>2</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>325.12</Station>
<OD>101.6</OD>
<ID>99.06</ID>
<Len>381.</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Parachute>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>22.6995</KnownMass>
<Density>0.006685</Density>
<Material>Rip stop nylon</Material>
<Name>Parachute</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>180.975</Xb>
<CalcMass>13.6872</CalcMass>
<CalcCG>38.0833</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>1</DensityType>
<PartNo>LP-18</PartNo>
<PartDesc>18 In. 6 lines</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>15</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(255,170,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>506.095</Station>
<Dia>456.999</Dia>
<SpillHoleDia>38.1</SpillHoleDia>
<SideCount>0</SideCount>
<ShroudLineCount>6</ShroudLineCount>
<Thickness>0.050038</Thickness>
<ShroudLineLen>457.2</ShroudLineLen>
<ChuteCount>1</ChuteCount>
<ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
<ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
<DragCoefficient>0.8</DragCoefficient>
<AttachedParts>
</AttachedParts>
</Parachute>
</AttachedParts>
</BodyTube>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>125.409</CalcMass>
<CalcCG>139.7</CalcCG>
<WettedSurface>0.0891805</WettedSurface>
<PaintedSurface>0.0891805</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC BT-3.9</PartNo>
<PartDesc>Airframe tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>3</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>706.12</Station>
<OD>101.6</OD>
<ID>99.06</ID>
<Len>279.4</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Tube coupler</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>596.9</Xb>
<CalcMass>62.4707</CalcMass>
<CalcCG>101.6</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>TC-3.90</PartNo>
<PartDesc>Tube Coupler</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>10</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>1</LocationMode>
<Color>rgb(255,255,127)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>596.9</Station>
<OD>99.06</OD>
<ID>97.282</ID>
<Len>203.2</Len>
<FinishCode>0</FinishCode>
<UsageCode>4</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Stiffy Coupler</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>603.25</Xb>
<CalcMass>184.074</CalcMass>
<CalcCG>95.25</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>STC-3.90</PartNo>
<PartDesc>Stiffy TC Stiffener</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>12</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>1</LocationMode>
<Color>rgb(166,147,40)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>603.25</Station>
<OD>99.1006</OD>
<ID>93.4009</ID>
<Len>190.5</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
</AttachedParts>
</BodyTube>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Bulkhead</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>79.375</Xb>
<CalcMass>32.3299</CalcMass>
<CalcCG>2.99974</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC BP-3.90</PartNo>
<PartDesc>Bulkhead Plate</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>13</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(230,204,56)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>785.495</Station>
<OD>97.282</OD>
<ID>0.</ID>
<Len>5.99948</Len>
<FinishCode>0</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Bulkhead</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>606.425</Xb>
<CalcMass>32.3299</CalcMass>
<CalcCG>2.99974</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC BP-3.90</PartNo>
<PartDesc>Bulkhead Plate</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>14</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>1</LocationMode>
<Color>rgb(230,204,56)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>606.425</Station>
<OD>97.282</OD>
<ID>0.</ID>
<Len>5.99948</Len>
<FinishCode>0</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<MassObject>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>340.194</KnownMass>
<Density>0.00102</Density>
<Material>1/16 In. braided nylon</Material>
<Name>EB-390</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<PartNo>EB-390</PartNo>
<PartDesc>EB-3.90 electronics bay</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>19</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>706.12</Station>
<TypeCode>0</TypeCode>
<Len>304.8</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</BodyTube>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>387.628</CalcMass>
<CalcCG>431.8</CalcCG>
<WettedSurface>0.275649</WettedSurface>
<PaintedSurface>0.275649</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC BT-3.9</PartNo>
<PartDesc>Airframe tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>4</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>985.52</Station>
<OD>101.6</OD>
<ID>99.06</ID>
<Len>863.6</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>431.8</Xb>
<CalcMass>129.536</CalcMass>
<CalcCG>215.9</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC MMT-2.14</PartNo>
<PartDesc>Motor mount tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>5</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(170,85,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1417.32</Station>
<OD>57.404</OD>
<ID>54.356</ID>
<Len>431.8</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>1</IsMotorMount>
<MotorDia>54.</MotorDia>
<EngineOverhang>0.50038</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>419.1</Xb>
<CalcMass>33.5224</CalcMass>
<CalcCG>2.99974</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC CR-3.9-2.14</PartNo>
<PartDesc>Centering Ring</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>6</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(230,204,56)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1836.42</Station>
<OD>99.06</OD>
<ID>57.404</ID>
<Len>5.99948</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>295.275</Xb>
<CalcMass>33.5224</CalcMass>
<CalcCG>2.99974</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC CR-3.9-2.14</PartNo>
<PartDesc>Centering Ring</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>7</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(230,204,56)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1712.6</Station>
<OD>99.06</OD>
<ID>57.404</ID>
<Len>5.99948</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>6.35</Xb>
<CalcMass>33.5224</CalcMass>
<CalcCG>2.99974</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC CR-3.9-2.14</PartNo>
<PartDesc>Centering Ring</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>8</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(230,204,56)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1423.67</Station>
<OD>99.06</OD>
<ID>57.404</ID>
<Len>5.99948</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
</AttachedParts>
</BodyTube>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Tube coupler</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>885.825</Xb>
<CalcMass>62.4707</CalcMass>
<CalcCG>101.6</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>TC-3.90</PartNo>
<PartDesc>Tube Coupler</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>9</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>1</LocationMode>
<Color>rgb(255,255,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>885.825</Station>
<OD>99.06</OD>
<ID>97.282</ID>
<Len>203.2</Len>
<FinishCode>0</FinishCode>
<UsageCode>4</UsageCode>
<AutoSize>1</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<CustomFinSet>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Fin set</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>539.75</Xb>
<CalcMass>325.342</CalcMass>
<CalcCG>203.169</CalcCG>
<WettedSurface>0.0446733</WettedSurface>
<PaintedSurface>0.13402</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>FS-PK77-35</PartNo>
<PartDesc>Fin set</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>21</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>8.02517</BarrowmanCNa>
<BarrowmanXN>1.66481</BarrowmanXN>
<RockSimCNa>12.9405</RockSimCNa>
<RockSimXN>1.68068</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1525.27</Station>
<FinCount>3</FinCount>
<RootChord>323.85</RootChord>
<TipChord>18.08</TipChord>
<SemiSpan>109.86</SemiSpan>
<MidChordLen>142.314</MidChordLen>
<SweepDistance>243.35</SweepDistance>
<Thickness>5.99948</Thickness>
<ShapeCode>2</ShapeCode>
<FinishCode>0</FinishCode>
<TipShapeCode>1</TipShapeCode>
<TabLength>117.475</TabLength>
<TabDepth>22.098</TabDepth>
<TabOffset>190.5</TabOffset>
<SweepMode>1</SweepMode>
<SweepAngle>0.</SweepAngle>
<RockSimXNPerFin>0.</RockSimXNPerFin>
<RockSimRadialXNPerFin>89.3546</RockSimRadialXNPerFin>
<RockSimCNaPerFin>7.47117</RockSimCNaPerFin>
<TaperRatio>0.0558283</TaperRatio>
<CantAngle>0.</CantAngle>
<CantPivotPoint>0.</CantPivotPoint>
<AverageChord>202.54</AverageChord>
<EffectiveTipChord>18.0776</EffectiveTipChord>
<PointList>323.85,0|323.85,19.05|285.75,109.855|209.55,109.855|0,0|</PointList>
<AutoCalcGridStepX>0,0,0,0,0,0,0</AutoCalcGridStepX>
<GridStepCountX>10,10,10,10,10,10,10</GridStepCountX>
<UseAbsoluteGridStepsX>0,0,0,0,0,0,0</UseAbsoluteGridStepsX>
<GridStepSizeX>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeX>
<SnapToSizeX>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeX>
<AutoCalcGridStepY>0,0,0,0,0,0,0</AutoCalcGridStepY>
<GridStepCountY>10,10,10,10,10,10,10</GridStepCountY>
<UseAbsoluteGridStepsY>0,0,0,0,0,0,0</UseAbsoluteGridStepsY>
<GridStepSizeY>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeY>
<SnapToSizeY>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeY>
<AttachedParts>
</AttachedParts>
</CustomFinSet>
<Parachute>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>170.001</KnownMass>
<Density>0.006685</Density>
<Material>Rip stop nylon</Material>
<Name>Parachute</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>190.5</Xb>
<CalcMass>98.4535</CalcMass>
<CalcCG>105.833</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>1</DensityType>
<PartNo>LP-50</PartNo>
<PartDesc>50 In. 10 lines</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>24</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(255,170,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1176.02</Station>
<Dia>1270.</Dia>
<SpillHoleDia>0.</SpillHoleDia>
<SideCount>0</SideCount>
<ShroudLineCount>10</ShroudLineCount>
<Thickness>0.050038</Thickness>
<ShroudLineLen>1350.</ShroudLineLen>
<ChuteCount>1</ChuteCount>
<ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
<ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
<DragCoefficient>0.8</DragCoefficient>
<AttachedParts>
</AttachedParts>
</Parachute>
<MassObject>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>79.3787</KnownMass>
<Density>0.00102</Density>
<Material>1/16 In. braided nylon</Material>
<Name>Shock cord mount</Name>
<KnownCG>412.75</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>412.75</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<PartNo>NW-15</PartNo>
<PartDesc>Shock cord</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>25</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>1398.27</Station>
<TypeCode>0</TypeCode>
<Len>304.8</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</BodyTube>
</Stage3Parts>
<Stage2Parts>
</Stage2Parts>
<Stage1Parts>
</Stage1Parts>
<SideViewDims>
</SideViewDims>
<BaseViewDims>
</BaseViewDims>
<VertViewDims>
</VertViewDims>
</RocketDesign>
</DesignInformation>
<SimulationResultsList>
<SimulationResults>
<MaxAltitude>159.789</MaxAltitude>
<MaxVelocity>53.5406</MaxVelocity>
<MaxAcceleration>65.6323</MaxAcceleration>
<TimeToApogee>6.094</TimeToApogee>
<OptimalDelay>5.044</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>1.05</TimeToBurnout>
<TimeToLanding>12.14</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>1.51712</MinLaunchGuideLen>
<MaxVertVelocity>53.5396</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>65.6323</MaxVertAcceleration>
<MaxHorzAcceleration>0.031226</MaxHorzAcceleration>
<MaxRange>10.5585</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2438.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.89408</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.12928</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[H165R-Plugged] </SimulationName>
<VelocityAtLaunchGuideEnd>17.3585</VelocityAtLaunchGuideEnd>
<WindStartAltitude>12.192</WindStartAltitude>
<TimeToWindShear>0.67</TimeToWindShear>
<TimeToFreeFlight>0.324</TimeToFreeFlight>
<TimeToMaxVelocity>0.982</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.4</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>500.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.053</ExecutionTime>
<RangeAtLanding>10.5585</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>50.8082</VelocityAtLanding>
<XVelcoityAtLanding>-0.228796</XVelcoityAtLanding>
<YVelocityAtLanding>-50.8077</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>10.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>2549.43</Mass0>
<CG0>1127.86</CG0>
<LaterialMOI0>4.00658e+06</LaterialMOI0>
<RadialMOI0>0.00385016</RadialMOI0>
<CP0>1356.73</CP0>
<CNA0>9.86139</CNA0>
<SM0>2.25266</SM0>
<GUID>{31a0437b-faa0-4579-b81a-45867ab17224}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>5.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>0</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>0</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>0</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>15</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>24</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>H165R</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>597.364</MaxAltitude>
<MaxVelocity>102.093</MaxVelocity>
<MaxAcceleration>47.6345</MaxAcceleration>
<TimeToApogee>12.006</TimeToApogee>
<OptimalDelay>8.49</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>3.516</TimeToBurnout>
<TimeToLanding>27.132</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>2.73217</MinLaunchGuideLen>
<MaxVertVelocity>102.048</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>47.6202</MaxVertAcceleration>
<MaxHorzAcceleration>0.27234</MaxHorzAcceleration>
<MaxRange>35.1673</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2438.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.89408</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.12928</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[I115W-Plugged] </SimulationName>
<VelocityAtLaunchGuideEnd>12.6334</VelocityAtLaunchGuideEnd>
<WindStartAltitude>12.192</WindStartAltitude>
<TimeToWindShear>0.978</TimeToWindShear>
<TimeToFreeFlight>0.522</TimeToFreeFlight>
<TimeToMaxVelocity>3.282</TimeToMaxVelocity>
<TimeToMaxAcceleration>1.342</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>500.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.105</ExecutionTime>
<RangeAtLanding>-34.9881</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>51.6661</VelocityAtLanding>
<XVelcoityAtLanding>-0.270107</XVelcoityAtLanding>
<YVelocityAtLanding>-51.6654</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>10.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>2925.43</Mass0>
<CG0>1211.93</CG0>
<LaterialMOI0>5.17745e+06</LaterialMOI0>
<RadialMOI0>0.00438032</RadialMOI0>
<CP0>1356.73</CP0>
<CNA0>9.86139</CNA0>
<SM0>1.42524</SM0>
<GUID>{9ee4173e-b3a2-4d4c-8853-b35be8e120e7}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>8.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>1</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>0</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>0</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>15</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>24</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>I115W</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>1163.38</MaxAltitude>
<MaxVelocity>199.825</MaxVelocity>
<MaxAcceleration>157.855</MaxAcceleration>
<TimeToApogee>14.3</TimeToApogee>
<OptimalDelay>12.694</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>1.606</TimeToBurnout>
<TimeToLanding>40.046</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>0.707984</MinLaunchGuideLen>
<MaxVertVelocity>199.8</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>157.855</MaxVertAcceleration>
<MaxHorzAcceleration>0.4072</MaxHorzAcceleration>
<MaxRange>21.5352</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2438.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.89408</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.12928</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[I350R-Plugged] </SimulationName>
<VelocityAtLaunchGuideEnd>25.7242</VelocityAtLaunchGuideEnd>
<WindStartAltitude>12.192</WindStartAltitude>
<TimeToWindShear>0.438</TimeToWindShear>
<TimeToFreeFlight>0.208</TimeToFreeFlight>
<TimeToMaxVelocity>1.536</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.502</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>500.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.124</ExecutionTime>
<RangeAtLanding>-4.64397</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>51.8225</VelocityAtLanding>
<XVelcoityAtLanding>-0.027519</XVelcoityAtLanding>
<YVelocityAtLanding>-51.8225</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>10.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>2961.43</Mass0>
<CG0>1197.93</CG0>
<LaterialMOI0>5.11008e+06</LaterialMOI0>
<RadialMOI0>0.00831951</RadialMOI0>
<CP0>1356.73</CP0>
<CNA0>9.86139</CNA0>
<SM0>1.56301</SM0>
<GUID>{0dc7f447-f063-40e8-8c75-686ba1233167}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>10.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>2</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>0</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>0</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>15</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>24</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>I350R</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>1278.85</MaxAltitude>
<MaxVelocity>198.931</MaxVelocity>
<MaxAcceleration>112.206</MaxAcceleration>
<TimeToApogee>15.172</TimeToApogee>
<OptimalDelay>12.608</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>2.564</TimeToBurnout>
<TimeToLanding>43.088</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>0.891411</MinLaunchGuideLen>
<MaxVertVelocity>198.837</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>112.206</MaxVertAcceleration>
<MaxHorzAcceleration>0.767548</MaxHorzAcceleration>
<MaxRange>51.6359</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2438.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.89408</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.12928</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[J270W-Plugged] </SimulationName>
<VelocityAtLaunchGuideEnd>22.5514</VelocityAtLaunchGuideEnd>
<WindStartAltitude>12.192</WindStartAltitude>
<TimeToWindShear>0.488</TimeToWindShear>
<TimeToFreeFlight>0.218</TimeToFreeFlight>
<TimeToMaxVelocity>2.294</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.008</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>500.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.153</ExecutionTime>
<RangeAtLanding>-28.2054</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>51.6019</VelocityAtLanding>
<XVelcoityAtLanding>-0.0356629</XVelcoityAtLanding>
<YVelocityAtLanding>-51.6019</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>10.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>2987.43</Mass0>
<CG0>1202.01</CG0>
<LaterialMOI0>5.18244e+06</LaterialMOI0>
<RadialMOI0>0.00854052</RadialMOI0>
<CP0>1356.73</CP0>
<CNA0>9.86139</CNA0>
<SM0>1.52285</SM0>
<GUID>{cc4bc112-2b11-4401-9ba3-dfa46b370745}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>12.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>3</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>0</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>0</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>15</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>24</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>J270W</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>1485.72</MaxAltitude>
<MaxVelocity>193.582</MaxVelocity>
<MaxAcceleration>103.672</MaxAcceleration>
<TimeToApogee>16.544</TimeToApogee>
<OptimalDelay>12.042</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>4.502</TimeToBurnout>
<TimeToLanding>47.662</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>0.955791</MinLaunchGuideLen>
<MaxVertVelocity>193.562</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>103.672</MaxVertAcceleration>
<MaxHorzAcceleration>0.269978</MaxHorzAcceleration>
<MaxRange>35.672</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2438.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.89408</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.12928</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[J180T-Plugged] </SimulationName>
<VelocityAtLaunchGuideEnd>21.8283</VelocityAtLaunchGuideEnd>
<WindStartAltitude>12.192</WindStartAltitude>
<TimeToWindShear>0.546</TimeToWindShear>
<TimeToFreeFlight>0.27</TimeToFreeFlight>
<TimeToMaxVelocity>3.122</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.1</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>500.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.149</ExecutionTime>
<RangeAtLanding>-30.8002</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>53.2025</VelocityAtLanding>
<XVelcoityAtLanding>-0.0118188</XVelcoityAtLanding>
<YVelocityAtLanding>-53.2025</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>10.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>3186.33</Mass0>
<CG0>1247.99</CG0>
<LaterialMOI0>5.89578e+06</LaterialMOI0>
<RadialMOI0>0.00634618</RadialMOI0>
<CP0>1356.73</CP0>
<CNA0>9.86139</CNA0>
<SM0>1.07029</SM0>
<GUID>{e64b681b-9330-4c0d-ac62-0a1b74447d74}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>12.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>4</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>0</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>0</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>15</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>24</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>J180T</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>1935.65</MaxAltitude>
<MaxVelocity>219.213</MaxVelocity>
<MaxAcceleration>65.3457</MaxAcceleration>
<TimeToApogee>19.456</TimeToApogee>
<OptimalDelay>12.454</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>7.002</TimeToBurnout>
<TimeToLanding>57.716</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>2.36138</MinLaunchGuideLen>
<MaxVertVelocity>218.601</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>65.0546</MaxVertAcceleration>
<MaxHorzAcceleration>1.44937</MaxHorzAcceleration>
<MaxRange>229.109</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>2438.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>152.4</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>0.89408</LaunchWindLowSpeed>
<LaunchWindHighSpeed>3.12928</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
<LaunchCCLow>8.</LaunchCCLow>
<LaunchCCHigh>8.</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[J135W-Plugged] </SimulationName>
<VelocityAtLaunchGuideEnd>13.6771</VelocityAtLaunchGuideEnd>
<WindStartAltitude>12.192</WindStartAltitude>
<TimeToWindShear>0.794</TimeToWindShear>
<TimeToFreeFlight>0.366</TimeToFreeFlight>
<TimeToMaxVelocity>4.752</TimeToMaxVelocity>
<TimeToMaxAcceleration>2.5</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>500.</SamplesPerSecond>
<SimulationType>4</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.192</ExecutionTime>
<RangeAtLanding>-198.545</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>53.6612</VelocityAtLanding>
<XVelcoityAtLanding>-0.0223852</XVelcoityAtLanding>
<YVelocityAtLanding>-53.6612</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>10.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>3471.13</Mass0>
<CG0>1265.54</CG0>
<LaterialMOI0>6.51802e+06</LaterialMOI0>
<RadialMOI0>0.0131784</RadialMOI0>
<CP0>1356.73</CP0>
<CNA0>9.86139</CNA0>
<SM0>0.897549</SM0>
<GUID>{277ed434-8043-4290-87de-d68a909962de}</GUID>
<WeatherCocking>1</WeatherCocking>
<RecommendedDelay>12.</RecommendedDelay>
<RecommendedMotor>0</RecommendedMotor>
<RecommendedMotorChecked>5</RecommendedMotorChecked>
<TrueIndex>0</TrueIndex>
<NinetyDegDanger>0</NinetyDegDanger>
<VelocityGuideSafe>0</VelocityGuideSafe>
<StaticMarginSafe>0</StaticMarginSafe>
<VelocityDeploySafe>0</VelocityDeploySafe>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>15</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
<SimulationEvent>
<PartSerialNo>24</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0</TestValueQ>
<WeatherCocking>0</WeatherCocking>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>J135W</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>5</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
</SimulationResultsList>
</RockSimDocument>
