<RockSimDocument>
<FileVersion>4</FileVersion>
<DesignInformation>
<RocketDesign>
<Name>LOC-1 Magnum</Name>
<CalculateCD>1</CalculateCD>
<ProCalculateCD>1</ProCalculateCD>
<ProCalculateCN>1</ProCalculateCN>
<FixedCd>0.75</FixedCd>
<FixedCd2>0.8</FixedCd2>
<FixedCd3>0.81</FixedCd3>
<FixedCd2Alone>0.95</FixedCd2Alone>
<FixedCd3Alone>0.95</FixedCd3Alone>
<StageCount>1</StageCount>
<Stage3Mass>0.</Stage3Mass>
<Stage2Mass>0.</Stage2Mass>
<Stage1Mass>0.</Stage1Mass>
<Stage321CG>0.</Stage321CG>
<Stage32CG>0.</Stage32CG>
<Stage3CG>0.</Stage3CG>
<Stage2CGAlone>0.</Stage2CGAlone>
<Stage1CGAlone>0.</Stage1CGAlone>
<CPCalcFlags>4</CPCalcFlags>
<LaunchGuideLength>914.4</LaunchGuideLength>
<UseKnownMass>0</UseKnownMass>
<DefaultFinish>0</DefaultFinish>
<FinishMedium>0</FinishMedium>
<FinishCoatCount>1</FinishCoatCount>
<GlueType>0</GlueType>
<Comments>Model reflects as-found component parameters adjusted for as-built conditions</Comments>
<Designer>Kit Designer: LOC Precision
Rocksim file created by M. Zapolski, Sr. NAR 98451 L2 05/16/2018</Designer>
<CPSimFlags>4</CPSimFlags>
<LastSerialNumber>19</LastSerialNumber>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<CameraState>CSV1|1|199.231,13.1756,-7.24796e-09|199.231,13.1756,809.159|0,1,0|703.973,943.518|30|2|809.159|0|0|0|0|0</CameraState>
<BarromanXN>0,327.378,0,0</BarromanXN>
<BarrowmanCNa>0,17.3682,0,0</BarrowmanCNa>
<RockSimXN>0,340.876,0,0</RockSimXN>
<RockSimCNa>0,25.7431,0,0</RockSimCNa>
<RockSimCNa90>0,0,0,0</RockSimCNa90>
<RockSimXN90>0,0,0,0</RockSimXN90>
<ViewType>0</ViewType>
<ViewStageCount>1</ViewStageCount>
<ViewTypeEdit>0</ViewTypeEdit>
<ViewStageCountEdit>1</ViewStageCountEdit>
<ZoomFactor>0.</ZoomFactor>
<ZoomFactorEdit>0.</ZoomFactorEdit>
<ScrollPosX>0</ScrollPosX>
<ScrollPosY>0</ScrollPosY>
<ScrollPosXEdit>0</ScrollPosXEdit>
<ScrollPosYEdit>0</ScrollPosYEdit>
<ThreeDFlags>0</ThreeDFlags>
<ThreeDFlagsEdit>0</ThreeDFlagsEdit>
<UseModelSprite>0</UseModelSprite>
<StaticMarginRef>0</StaticMarginRef>
<UserRefDiameter>0.</UserRefDiameter>
<SideMarkerHeight>9.99998</SideMarkerHeight>
<SideDimensionHeight>9.99998</SideDimensionHeight>
<BaseMarkerHeight>9.99998</BaseMarkerHeight>
<BaseDimensionHeight>9.99998</BaseDimensionHeight>
<ShowGlideCP>0</ShowGlideCP>
<ShowGridTypeSide>1</ShowGridTypeSide>
<ShowGridTypeBase>1</ShowGridTypeBase>
<GridSpacing>12.7</GridSpacing>
<GridOpacity>0.35</GridOpacity>
<GridColor>rgb(85,170,255)</GridColor>
<MaxDiaWithFins>110.86</MaxDiaWithFins>
<MaxDiaWithoutFins>25.273</MaxDiaWithoutFins>
<MaxLenWithFins>398.462</MaxLenWithFins>
<MaxLenWithoutFins>398.462</MaxLenWithoutFins>
<MinXExtent>0.</MinXExtent>
<MaxXExtent>398.462</MaxXExtent>
<CalculatedMaxStageDia>0,25.273,0,0</CalculatedMaxStageDia>
<CalculatedStageLen>0,398.462,0,0</CalculatedStageLen>
<Cd3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd3>
<Cd32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd32>
<Cd321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cd321>
<Cb3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb3>
<Cb32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb32>
<Cb321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb321>
<CNa3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa3>
<CNa32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa32>
<CNa321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa321>
<CP3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP3>
<CP32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP32>
<CP321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP321>
<SimulationEventList>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEventList>
<Stage3Parts>
<NoseCone>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1050.</Density>
<Material>Polystyrene (PS)</Material>
<Name>Nose cone</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>10.21</CalcMass>
<CalcCG>73.5969</CalcCG>
<WettedSurface>0.00540776</WettedSurface>
<PaintedSurface>0.00540776</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>1</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(170,0,255)</Color>
<BarrowmanCNa>2.</BarrowmanCNa>
<BarrowmanXN>0.0508</BarrowmanXN>
<RockSimCNa>2.</RockSimCNa>
<RockSimXN>0.0508</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>0.</Station>
<Len>101.6</Len>
<BaseDia>25.273</BaseDia>
<FinishCode>1</FinishCode>
<ShapeCode>2</ShapeCode>
<ConstructionType>1</ConstructionType>
<ShoulderLen>16.67</ShoulderLen>
<WallThickness>1.51181</WallThickness>
<ShapeParameter>0.</ShapeParameter>
<ShoulderOD>23.8252</ShoulderOD>
<BaseExtensionLen>0.</BaseExtensionLen>
<CoreDia>0.</CoreDia>
<CoreLen>0.</CoreLen>
<AttachedParts>
</AttachedParts>
</NoseCone>
<BodyTube>
<PartMfg>Custom</PartMfg>
<KnownMass>3.05</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Payload BT</Name>
<KnownCG>34.13</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>2.8026</CalcMass>
<CalcCG>34.1313</CalcCG>
<WettedSurface>0.00541987</WettedSurface>
<PaintedSurface>0.00541987</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>2</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>101.6</Station>
<OD>25.273</OD>
<ID>24.3332</ID>
<Len>68.2625</Len>
<FinishCode>1</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>Custom</PartMfg>
<KnownMass>2.36</KnownMass>
<Density>688.794</Density>
<Material>Cardboard</Material>
<Name>Tube coupler</Name>
<KnownCG>25.4</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>44.45</Xb>
<CalcMass>2.06066</CalcMass>
<CalcCG>25.4</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>4</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(85,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>146.05</Station>
<OD>23.876</OD>
<ID>22.2504</ID>
<Len>50.8</Len>
<FinishCode>3</FinishCode>
<UsageCode>4</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>0.35</KnownMass>
<Density>0.000659</Density>
<Material>1/32 In. kevlar</Material>
<Name>NC-Payload Asm Glue</Name>
<KnownCG>57.15</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>57.15</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>16</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(170,85,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>158.75</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</BodyTube>
<BodyTube>
<PartMfg>Custom</PartMfg>
<KnownMass>9.2</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Main BT</Name>
<KnownCG>114.3</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>9.38546</CalcMass>
<CalcCG>114.3</CalcCG>
<WettedSurface>0.0181503</WettedSurface>
<PaintedSurface>0.0181503</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>3</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>169.863</Station>
<OD>25.273</OD>
<ID>24.3332</ID>
<Len>228.6</Len>
<FinishCode>1</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>Custom</PartMfg>
<KnownMass>1.1</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (Birch)</Material>
<Name><![CDATA[Bkhd & Eye Screw]]></Name>
<KnownCG>1.5875</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>23.8125</Xb>
<CalcMass>0.882736</CalcMass>
<CalcCG>1.5621</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>14</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(255,0,127)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>193.675</Station>
<OD>22.2758</OD>
<ID>0.</ID>
<Len>3.1242</Len>
<FinishCode>3</FinishCode>
<UsageCode>1</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Streamer>
<PartMfg>DIY</PartMfg>
<KnownMass>4.58</KnownMass>
<Density>920.</Density>
<Material>Polyethylene (LD-PE)</Material>
<Name>Streamer</Name>
<KnownCG>12.7</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>44.45</Xb>
<CalcMass>3.52781</CalcMass>
<CalcCG>12.7</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>rgb(255,50,54)</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>11</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(255,170,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>214.312</Station>
<Len>1981.2</Len>
<Width>25.4</Width>
<Thickness>0.0762</Thickness>
<StreamerCount>1</StreamerCount>
<DragCoefficient>0.252</DragCoefficient>
<IsFolded>1</IsFolded>
<AutoCalcCd>1</AutoCalcCd>
<AttachedParts>
</AttachedParts>
</Streamer>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>0.</KnownMass>
<Density>0.000659</Density>
<Material>1/32 In. kevlar</Material>
<Name>Shock Cord</Name>
<KnownCG>82.55</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>82.55</Xb>
<CalcMass>0.753237</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>13</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(170,85,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>252.412</Station>
<TypeCode>1</TypeCode>
<Len>1143.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
<BodyTube>
<PartMfg>Estes</PartMfg>
<KnownMass>1.23</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>MMT</Name>
<KnownCG>34.925</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>1.02439</CalcMass>
<CalcCG>34.925</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>6</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(255,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>328.613</Station>
<OD>18.4404</OD>
<ID>17.9832</ID>
<Len>69.85</Len>
<FinishCode>3</FinishCode>
<IsMotorMount>1</IsMotorMount>
<MotorDia>18.</MotorDia>
<EngineOverhang>6.35</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>Custom</PartMfg>
<KnownMass>0.66</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>FCR</Name>
<KnownCG>2.286</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>6.35</Xb>
<CalcMass>2.29561</CalcMass>
<CalcCG>2.2479</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>8</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,170,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>334.962</Station>
<OD>24.0792</OD>
<ID>18.8976</ID>
<Len>4.4958</Len>
<FinishCode>3</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<Ring>
<PartMfg>Custom</PartMfg>
<KnownMass>0.64</KnownMass>
<Density>688.794</Density>
<Material>Cardboard</Material>
<Name>ACR</Name>
<KnownCG>2.286</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>3.175</Xb>
<CalcMass>1.41017</CalcMass>
<CalcCG>2.2479</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>9</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(0,170,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>390.792</Station>
<OD>24.0792</OD>
<ID>18.8976</ID>
<Len>4.4958</Len>
<FinishCode>3</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<BodyTube>
<PartMfg>Estes</PartMfg>
<KnownMass>0.45</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Mtr Blk</Name>
<KnownCG>2.286</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>0.584972</CalcMass>
<CalcCG>2.2479</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>10</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>rgb(0,0,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>328.613</Station>
<OD>17.653</OD>
<ID>12.8016</ID>
<Len>4.4958</Len>
<FinishCode>3</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
</AttachedParts>
</BodyTube>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>1.</KnownMass>
<Density>0.00205</Density>
<Material>1/8 In. flat elastic</Material>
<Name>Motor Hook</Name>
<KnownCG>22.225</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>22.225</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>12</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(170,85,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>376.238</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</BodyTube>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>0.2</KnownMass>
<Density>0.000659</Density>
<Material>1/32 In. kevlar</Material>
<Name>MMT-BT Glue</Name>
<KnownCG>34.925</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>34.925</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>17</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(170,85,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>363.537</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
<CustomFinSet>
<PartMfg>Custom</PartMfg>
<KnownMass>0.</KnownMass>
<Density>361.377</Density>
<Material>1/16 Aircraft Plywood</Material>
<Name>Fin set</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>3.175</Xb>
<CalcMass>5.7399</CalcMass>
<CalcCG>36.1678</CalcCG>
<WettedSurface>0.00325875</WettedSurface>
<PaintedSurface>0.00977625</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>rgb(255,0,0)</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>7</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(0,85,0)</Color>
<BarrowmanCNa>15.3682</BarrowmanCNa>
<BarrowmanXN>0.363371</BarrowmanXN>
<RockSimCNa>23.7431</RockSimCNa>
<RockSimXN>0.36531</RockSimXN>
<SimpleColorModel>0</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>337.375</Station>
<FinCount>3</FinCount>
<RootChord>57.91</RootChord>
<TipChord>7.06</TipChord>
<SemiSpan>42.79</SemiSpan>
<MidChordLen>46.6001</MidChordLen>
<SweepDistance>43.88</SweepDistance>
<Thickness>3.02768</Thickness>
<ShapeCode>2</ShapeCode>
<FinishCode>1</FinishCode>
<TipShapeCode>0</TipShapeCode>
<TabLength>34.925</TabLength>
<TabDepth>3.4163</TabDepth>
<TabOffset>17.4625</TabOffset>
<SweepMode>1</SweepMode>
<SweepAngle>0.</SweepAngle>
<RockSimXNPerFin>0.</RockSimXNPerFin>
<RockSimRadialXNPerFin>28.4511</RockSimRadialXNPerFin>
<RockSimCNaPerFin>13.7081</RockSimCNaPerFin>
<TaperRatio>0.121913</TaperRatio>
<CantAngle>0.</CantAngle>
<CantPivotPoint>0.</CantPivotPoint>
<AverageChord>37.79</AverageChord>
<EffectiveTipChord>7.06248</EffectiveTipChord>
<PointList>57.912,0|59.5069,33.4387|36.6121,42.7935|0,0|</PointList>
<AutoCalcGridStepX>0,0,0,0,0,0,0</AutoCalcGridStepX>
<GridStepCountX>10,10,10,10,10,10,10</GridStepCountX>
<UseAbsoluteGridStepsX>0,0,0,0,0,0,0</UseAbsoluteGridStepsX>
<GridStepSizeX>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeX>
<SnapToSizeX>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeX>
<AutoCalcGridStepY>0,0,0,0,0,0,0</AutoCalcGridStepY>
<GridStepCountY>10,10,10,10,10,10,10</GridStepCountY>
<UseAbsoluteGridStepsY>0,0,0,0,0,0,0</UseAbsoluteGridStepsY>
<GridStepSizeY>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeY>
<SnapToSizeY>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeY>
<AttachedParts>
</AttachedParts>
</CustomFinSet>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>0.24</KnownMass>
<Density>0.000659</Density>
<Material>1/32 In. kevlar</Material>
<Name>Fin Set Glue</Name>
<KnownCG>28.575</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>28.575</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>18</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(170,85,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>369.887</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
<LaunchLug>
<PartMfg>Apogee</PartMfg>
<KnownMass>0.08</KnownMass>
<Density>848.979</Density>
<Material>Spiral/Glassine</Material>
<Name>Launch lug</Name>
<KnownCG>12.7</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>66.675</Xb>
<CalcMass>0.0573432</CalcMass>
<CalcCG>12.7</CalcCG>
<WettedSurface>0.000667459</WettedSurface>
<PaintedSurface>0.000348615</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>13051</PartNo>
<PartDesc><![CDATA["1/8"" X 1"]]></PartDesc>
<RadialLoc>14.8209</RadialLoc>
<RadialAngle>1.0472</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(255,0,0)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>15</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(0,0,250)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>306.387</Station>
<OD>4.3688</OD>
<ID>3.9624</ID>
<Len>25.4</Len>
<FinishCode>1</FinishCode>
<AttachedParts>
</AttachedParts>
</LaunchLug>
<MassObject>
<PartMfg>Custom</PartMfg>
<KnownMass>0.03</KnownMass>
<Density>0.000659</Density>
<Material>1/32 In. kevlar</Material>
<Name>LL Glue</Name>
<KnownCG>73.025</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>73.025</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>rgb(0,0,250)</AbientColor>
<DiffuseColor>rgb(0,0,250)</DiffuseColor>
<SpecularColor>rgb(255,255,255)</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>19</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>2</LocationMode>
<Color>rgb(170,85,0)</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>325.437</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</BodyTube>
</Stage3Parts>
<Stage2Parts>
</Stage2Parts>
<Stage1Parts>
</Stage1Parts>
<SideViewDims>
</SideViewDims>
<BaseViewDims>
</BaseViewDims>
<VertViewDims>
</VertViewDims>
</RocketDesign>
</DesignInformation>
<SimulationResultsList>
<SimulationResults>
<MaxAltitude>60.611</MaxAltitude>
<MaxVelocity>33.0281</MaxVelocity>
<MaxAcceleration>160.076</MaxAcceleration>
<TimeToApogee>3.71875</TimeToApogee>
<OptimalDelay>2.9875</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>1.46135</VelocityAtDeplyment>
<AltitudeAtDeployment>60.6103</AltitudeAtDeployment>
<DelayTime>3</DelayTime>
<EjectTime>3.73</EjectTime>
<FinalState>2</FinalState>
<TimeToBurnout>0.73125</TimeToBurnout>
<TimeToLanding>11.5088</TimeToLanding>
<TimeToEject>3.73</TimeToEject>
<MinLaunchGuideLen>0.742178</MinLaunchGuideLen>
<MaxVertVelocity>32.9834</MaxVertVelocity>
<MaxHorzVelocity>2.2352</MaxHorzVelocity>
<MaxVertAcceleration>160.076</MaxVertAcceleration>
<MaxHorzAcceleration>0.18312</MaxHorzAcceleration>
<MaxRange>13.9729</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>1219.2</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>757.936</LaunchBarometer>
<LaunchLatitude>39.466</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>66.</LaunchHumidity>
<LaunchTemperature>17.7778</LaunchTemperature>
<LaunchAltitude>33.528</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>2.2352</LaunchWindLowSpeed>
<LaunchWindHighSpeed>2.2352</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>3</LaunchCloudCoverPreset>
<LaunchCCLow>0.3</LaunchCCLow>
<LaunchCCHigh>0.69</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[A8-3] </SimulationName>
<VelocityAtLaunchGuideEnd>17.7936</VelocityAtLaunchGuideEnd>
<WindStartAltitude>1.8288</WindStartAltitude>
<Comments>Rabbit Hill Farm: Lat: 39.466; El: 110 ft.</Comments>
<TimeToWindShear>0.28375</TimeToWindShear>
<TimeToFreeFlight>0.25125</TimeToFreeFlight>
<TimeToMaxVelocity>0.695</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.22625</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>1</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.056</ExecutionTime>
<RangeAtLanding>13.9729</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>8.41275</VelocityAtLanding>
<XVelcoityAtLanding>0.</XVelcoityAtLanding>
<YVelocityAtLanding>-8.41275</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,3.73,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,3.73,0,0</TimeToDeployment>
<DeploymentType>32,32,83,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>58.2276</Mass0>
<CG0>266.419</CG0>
<LaterialMOI0>4937.27</LaterialMOI0>
<RadialMOI0>9.64803e-06</RadialMOI0>
<CP0>340.876</CP0>
<CNA0>25.7431</CNA0>
<SM0>2.94609</SM0>
<GUID>{1086b19a-1502-4f6e-b5b5-72ab919db0da}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>60.6103</DeployedAt_Altitude>
<DeployedAt_Velocity>1.46135</DeployedAt_Velocity>
<DeployedAt_Range>-2.92797</DeployedAt_Range>
<DeployedAt_Time>3.73</DeployedAt_Time>
<DeviceID>256</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>A8</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Estes</EngineMfg>
<EngineOverhang>6.35</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>6</MountSerialNo>
<EjectionDelay>3.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>162.128</MaxAltitude>
<MaxVelocity>63.2699</MaxVelocity>
<MaxAcceleration>195.346</MaxAcceleration>
<TimeToApogee>5.51375</TimeToApogee>
<OptimalDelay>4.6525</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>8.57108</VelocityAtDeplyment>
<AltitudeAtDeployment>159.762</AltitudeAtDeployment>
<DelayTime>4</DelayTime>
<EjectTime>4.86</EjectTime>
<FinalState>0</FinalState>
<TimeToBurnout>0.86125</TimeToBurnout>
<TimeToLanding>25.3825</TimeToLanding>
<TimeToEject>4.86</TimeToEject>
<MinLaunchGuideLen>0.630367</MinLaunchGuideLen>
<MaxVertVelocity>63.1629</MaxVertVelocity>
<MaxHorzVelocity>2.2352</MaxHorzVelocity>
<MaxVertAcceleration>195.346</MaxVertAcceleration>
<MaxHorzAcceleration>2.89436</MaxHorzAcceleration>
<MaxRange>33.3303</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>1219.2</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>757.936</LaunchBarometer>
<LaunchLatitude>39.466</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>66.</LaunchHumidity>
<LaunchTemperature>17.7778</LaunchTemperature>
<LaunchAltitude>33.528</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>2.2352</LaunchWindLowSpeed>
<LaunchWindHighSpeed>2.2352</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>3</LaunchCloudCoverPreset>
<LaunchCCLow>0.3</LaunchCCLow>
<LaunchCCHigh>0.69</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[B6-4] </SimulationName>
<VelocityAtLaunchGuideEnd>19.9742</VelocityAtLaunchGuideEnd>
<WindStartAltitude>1.8288</WindStartAltitude>
<Comments>Rabbit Hill Farm: Lat: 39.466; El: 110 ft.</Comments>
<TimeToWindShear>0.2375</TimeToWindShear>
<TimeToFreeFlight>0.20875</TimeToFreeFlight>
<TimeToMaxVelocity>0.83375</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.17125</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>1</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.095</ExecutionTime>
<RangeAtLanding>33.3303</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>8.37978</VelocityAtLanding>
<XVelcoityAtLanding>0.</XVelcoityAtLanding>
<YVelocityAtLanding>-8.37978</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,4.86,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,4.86,0,0</TimeToDeployment>
<DeploymentType>32,32,83,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>60.0979</Mass0>
<CG0>269.637</CG0>
<LaterialMOI0>5192.95</LaterialMOI0>
<RadialMOI0>1.02726e-05</RadialMOI0>
<CP0>340.876</CP0>
<CNA0>25.7431</CNA0>
<SM0>2.81878</SM0>
<GUID>{8406be9d-1130-4945-a066-a32561867dd1}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>159.762</DeployedAt_Altitude>
<DeployedAt_Velocity>8.57108</DeployedAt_Velocity>
<DeployedAt_Range>-9.32936</DeployedAt_Range>
<DeployedAt_Time>4.86</DeployedAt_Time>
<DeviceID>256</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>B6</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Estes</EngineMfg>
<EngineOverhang>6.35</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>6</MountSerialNo>
<EjectionDelay>4.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>373.1</MaxAltitude>
<MaxVelocity>108.11</MaxVelocity>
<MaxAcceleration>210.123</MaxAcceleration>
<TimeToApogee>7.7275</TimeToApogee>
<OptimalDelay>5.86625</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>15.046</VelocityAtDeplyment>
<AltitudeAtDeployment>368.374</AltitudeAtDeployment>
<DelayTime>5</DelayTime>
<EjectTime>6.86125</EjectTime>
<FinalState>0</FinalState>
<TimeToBurnout>1.86125</TimeToBurnout>
<TimeToLanding>52.5912</TimeToLanding>
<TimeToEject>6.86125</TimeToEject>
<MinLaunchGuideLen>0.631203</MinLaunchGuideLen>
<MaxVertVelocity>107.645</MaxVertVelocity>
<MaxHorzVelocity>2.2352</MaxHorzVelocity>
<MaxVertAcceleration>210.123</MaxVertAcceleration>
<MaxHorzAcceleration>9.92328</MaxHorzAcceleration>
<MaxRange>62.2976</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>1219.2</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>757.936</LaunchBarometer>
<LaunchLatitude>39.466</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>66.</LaunchHumidity>
<LaunchTemperature>17.7778</LaunchTemperature>
<LaunchAltitude>33.528</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>2.2352</LaunchWindLowSpeed>
<LaunchWindHighSpeed>2.2352</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>3</LaunchCloudCoverPreset>
<LaunchCCLow>0.3</LaunchCCLow>
<LaunchCCHigh>0.69</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[C6-5] </SimulationName>
<VelocityAtLaunchGuideEnd>20.1892</VelocityAtLaunchGuideEnd>
<WindStartAltitude>1.8288</WindStartAltitude>
<Comments>Rabbit Hill Farm: Lat: 39.466; El: 110 ft.</Comments>
<TimeToWindShear>0.24</TimeToWindShear>
<TimeToFreeFlight>0.21125</TimeToFreeFlight>
<TimeToMaxVelocity>1.84</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.19125</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>1</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.148</ExecutionTime>
<RangeAtLanding>62.2976</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>8.35513</VelocityAtLanding>
<XVelcoityAtLanding>0.</XVelcoityAtLanding>
<YVelocityAtLanding>-8.35513</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,6.86125,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,6.86125,0,0</TimeToDeployment>
<DeploymentType>32,32,83,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>64.9779</Mass0>
<CG0>277.16</CG0>
<LaterialMOI0>5860.97</LaterialMOI0>
<RadialMOI0>1.19025e-05</RadialMOI0>
<CP0>340.876</CP0>
<CNA0>25.7431</CNA0>
<SM0>2.52109</SM0>
<GUID>{32c6e6b5-d6ad-48d8-ad91-90bbc2e97f32}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>368.374</DeployedAt_Altitude>
<DeployedAt_Velocity>15.046</DeployedAt_Velocity>
<DeployedAt_Range>-34.8703</DeployedAt_Range>
<DeployedAt_Time>6.86125</DeployedAt_Time>
<DeviceID>256</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>C6</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Estes</EngineMfg>
<EngineOverhang>6.35</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>6</MountSerialNo>
<EjectionDelay>5.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>660.813</MaxAltitude>
<MaxVelocity>240.337</MaxVelocity>
<MaxAcceleration>470.808</MaxAcceleration>
<TimeToApogee>8.75625</TimeToApogee>
<OptimalDelay>7.815</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>11.6614</VelocityAtDeplyment>
<AltitudeAtDeployment>656.942</AltitudeAtDeployment>
<DelayTime>7</DelayTime>
<EjectTime>7.94125</EjectTime>
<FinalState>0</FinalState>
<TimeToBurnout>0.94125</TimeToBurnout>
<TimeToLanding>79.5637</TimeToLanding>
<TimeToEject>7.94125</TimeToEject>
<MinLaunchGuideLen>0.204215</MinLaunchGuideLen>
<MaxVertVelocity>240.164</MaxVertVelocity>
<MaxHorzVelocity>2.2352</MaxHorzVelocity>
<MaxVertAcceleration>470.808</MaxVertAcceleration>
<MaxHorzAcceleration>5.50127</MaxHorzAcceleration>
<MaxRange>132.967</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>1219.2</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>757.936</LaunchBarometer>
<LaunchLatitude>39.466</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>66.</LaunchHumidity>
<LaunchTemperature>17.7778</LaunchTemperature>
<LaunchAltitude>33.528</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>99</LaunchWindPreset>
<LaunchWindLowSpeed>2.2352</LaunchWindLowSpeed>
<LaunchWindHighSpeed>2.2352</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>3</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.04</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>3</LaunchCloudCoverPreset>
<LaunchCCLow>0.3</LaunchCCLow>
<LaunchCCHigh>0.69</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[D21T-7] </SimulationName>
<VelocityAtLaunchGuideEnd>33.0638</VelocityAtLaunchGuideEnd>
<WindStartAltitude>1.8288</WindStartAltitude>
<Comments>Rabbit Hill Farm: Lat: 39.466; El: 110 ft.</Comments>
<TimeToWindShear>0.11</TimeToWindShear>
<TimeToFreeFlight>0.09125</TimeToFreeFlight>
<TimeToMaxVelocity>0.795</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.03</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>1</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.216</ExecutionTime>
<RangeAtLanding>132.967</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>8.59092</VelocityAtLanding>
<XVelcoityAtLanding>0.</XVelcoityAtLanding>
<YVelocityAtLanding>-8.59092</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,7.94125,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,7.94125,0,0</TimeToDeployment>
<DeploymentType>32,32,83,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>66.8779</Mass0>
<CG0>279.793</CG0>
<LaterialMOI0>6121.29</LaterialMOI0>
<RadialMOI0>1.25371e-05</RadialMOI0>
<CP0>340.876</CP0>
<CNA0>25.7431</CNA0>
<SM0>2.41694</SM0>
<GUID>{b9a358df-2527-464e-b995-ab588e948c09}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>11</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>656.942</DeployedAt_Altitude>
<DeployedAt_Velocity>11.6614</DeployedAt_Velocity>
<DeployedAt_Range>-23.5014</DeployedAt_Range>
<DeployedAt_Time>7.94125</DeployedAt_Time>
<DeviceID>256</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>D21T</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>6.35</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>6</MountSerialNo>
<EjectionDelay>7.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
</SimulationResultsList>
</RockSimDocument>
