<RockSimDocument>
  <FileVersion>4</FileVersion>
  <DesignInformation>
    <RocketDesign>
      <Name>Xeno</Name>
      <CalculateCD>1</CalculateCD>
      <ProCalculateCD>1</ProCalculateCD>
      <ProCalculateCN>1</ProCalculateCN>
      <FixedCd>0.75</FixedCd>
      <FixedCd2>0.8</FixedCd2>
      <FixedCd3>0.81</FixedCd3>
      <FixedCd2Alone>0.95</FixedCd2Alone>
      <FixedCd3Alone>0.95</FixedCd3Alone>
      <StageCount>1</StageCount>
      <Stage3Mass>0.</Stage3Mass>
      <Stage2Mass>0.</Stage2Mass>
      <Stage1Mass>0.</Stage1Mass>
      <Stage321CG>0.</Stage321CG>
      <Stage32CG>0.</Stage32CG>
      <Stage3CG>0.</Stage3CG>
      <Stage2CGAlone>0.</Stage2CGAlone>
      <Stage1CGAlone>0.</Stage1CGAlone>
      <CPCalcFlags>1</CPCalcFlags>
      <LaunchGuideLength>914.4</LaunchGuideLength>
      <UseKnownMass>0</UseKnownMass>
      <DefaultFinish>0</DefaultFinish>
      <FinishMedium>0</FinishMedium>
      <FinishCoatCount>1</FinishCoatCount>
      <GlueType>0</GlueType>
      <CPSimFlags>1</CPSimFlags>
      <LastSerialNumber>9</LastSerialNumber>
      <DisplayFlags>1</DisplayFlags>
      <MetricsFlags>0</MetricsFlags>
      <BarromanXN>0,271.684,0,0</BarromanXN>
      <BarrowmanCNa>0,10.3919,0,0</BarrowmanCNa>
      <RockSimXN>0,290.002,0,0</RockSimXN>
      <RockSimCNa>0,15.035,0,0</RockSimCNa>
      <RockSimCNa90>0,0,0,0</RockSimCNa90>
      <RockSimXN90>0,0,0,0</RockSimXN90>
      <ViewType>0</ViewType>
      <ViewStageCount>1</ViewStageCount>
      <ViewTypeEdit>0</ViewTypeEdit>
      <ViewStageCountEdit>1</ViewStageCountEdit>
      <ZoomFactor>0.</ZoomFactor>
      <ZoomFactorEdit>0.</ZoomFactorEdit>
      <ScrollPosX>0</ScrollPosX>
      <ScrollPosY>0</ScrollPosY>
      <ScrollPosXEdit>0</ScrollPosXEdit>
      <ScrollPosYEdit>0</ScrollPosYEdit>
      <ThreeDFlags>0</ThreeDFlags>
      <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
      <UseModelSprite>0</UseModelSprite>
      <StaticMarginRef>0</StaticMarginRef>
      <UserRefDiameter>0.</UserRefDiameter>
      <SideMarkerHeight>9.99998</SideMarkerHeight>
      <SideDimensionHeight>9.99998</SideDimensionHeight>
      <BaseMarkerHeight>9.99998</BaseMarkerHeight>
      <BaseDimensionHeight>9.99998</BaseDimensionHeight>
      <ShowGlideCP>0</ShowGlideCP>
      <ShowGridTypeSide>0</ShowGridTypeSide>
      <ShowGridTypeBase>0</ShowGridTypeBase>
      <GridSpacing>10.</GridSpacing>
      <GridOpacity>0.15</GridOpacity>
      <GridColor>black</GridColor>
      <MaxDiaWithFins>86.36</MaxDiaWithFins>
      <MaxDiaWithoutFins>25.4</MaxDiaWithoutFins>
      <MaxLenWithFins>368.3</MaxLenWithFins>
      <MaxLenWithoutFins>342.9</MaxLenWithoutFins>
      <MinXExtent>0.</MinXExtent>
      <MaxXExtent>368.3</MaxXExtent>
      <CalculatedMaxStageDia>0,25.4,0,0</CalculatedMaxStageDia>
      <CalculatedStageLen>0,342.9,0,0</CalculatedStageLen>
      <Cd3>
        <PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
        <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
        <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
        <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
        <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
      </PolyData>
    </Cd3>
    <Cd32>
      <PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
      <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
      <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
      <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
      <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
    </PolyData>
  </Cd32>
  <Cd321>
    <PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
    <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
    <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
    <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
    <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
  </PolyData>
</Cd321>
<Cb3>
  <PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
  <X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
  <A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
  <B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
  <C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb3>
<Cb32>
<PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb32>
<Cb321>
<PolyData  useXYOnly="1" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</Cb321>
<CNa3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa3>
<CNa32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa32>
<CNa321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CNa321>
<CP3>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP3>
<CP32>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP32>
<CP321>
<PolyData  useXYOnly="0" useSmoothCurveEvaluation="0" count="0">
<X-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</X-data>
<A-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</A-data>
<B-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</B-data>
<C-data>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</C-data>
</PolyData>
</CP321>
<SimulationEventList>
<SimulationEvent>
<PartSerialNo>7</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEventList>
<Stage3Parts>
<NoseCone>
<PartMfg>LOC</PartMfg>
<KnownMass>12.0004</KnownMass>
<Density>1049.21</Density>
<Material>Polystyrene PS</Material>
<Name>Nose cone</Name>
<KnownCG>72.9996</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>8.61397</CalcMass>
<CalcCG>87.4731</CalcCG>
<WettedSurface>0.00579022</WettedSurface>
<PaintedSurface>0.00579022</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>PNC-1.0Long</PartNo>
<PartDesc>24mm 4:1 cone</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>1</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>2.</BarrowmanCNa>
<BarrowmanXN>0.0501495</BarrowmanXN>
<RockSimCNa>2.</RockSimCNa>
<RockSimXN>0.0501495</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>0.</Station>
<Len>107.95</Len>
<BaseDia>25.4</BaseDia>
<FinishCode>0</FinishCode>
<ShapeCode>1</ShapeCode>
<ConstructionType>1</ConstructionType>
<ShoulderLen>25.4</ShoulderLen>
<WallThickness>1.00076</WallThickness>
<ShapeParameter>0.</ShapeParameter>
<ShoulderOD>24.384</ShoulderOD>
<BaseExtensionLen>6.35</BaseExtensionLen>
<CoreDia>0.</CoreDia>
<CoreLen>0.</CoreLen>
<AttachedParts>
</AttachedParts>
</NoseCone>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>12.6636</CalcMass>
<CalcCG>114.3</CalcCG>
<WettedSurface>0.0182415</WettedSurface>
<PaintedSurface>0.0182415</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC MMT-0.95</PartNo>
<PartDesc>Motor mount tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>2</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>114.3</Station>
<OD>25.4</OD>
<ID>24.13</ID>
<Len>228.6</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>0</IsMotorMount>
<MotorDia>0.</MotorDia>
<EngineOverhang>0.5</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>0</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<BodyTube>
<PartMfg>LOC/Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>1121.29</Density>
<Material>Paper</Material>
<Name>Body tube</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>158.75</Xb>
<CalcMass>0.739318</CalcMass>
<CalcCG>34.925</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC MMT-0.75</PartNo>
<PartDesc>Motor mount tube</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>3</SerialNo>
<DisplayFlags>1</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>273.05</Station>
<OD>18.3642</OD>
<ID>18.034</ID>
<Len>69.85</Len>
<FinishCode>0</FinishCode>
<IsMotorMount>1</IsMotorMount>
<MotorDia>18.</MotorDia>
<EngineOverhang>0.50038</EngineOverhang>
<FrontExtension>0.</FrontExtension>
<RearExtension>0.</RearExtension>
<IsInsideTube>1</IsInsideTube>
<isStrapOnTube>0</isStrapOnTube>
<AttachedParts>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>0.</Xb>
<CalcMass>1.5253</CalcMass>
<CalcCG>2.3495</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC FCR-1.0x75</PartNo>
<PartDesc>Centering Ring</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>4</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>273.05</Station>
<OD>23.876</OD>
<ID>18.796</ID>
<Len>4.699</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
</AttachedParts>
</BodyTube>
<Ring>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>Centering ring</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>222.25</Xb>
<CalcMass>1.5253</CalcMass>
<CalcCG>2.3495</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>LOC FCR-1.0x75</PartNo>
<PartDesc>Centering Ring</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>5</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>336.55</Station>
<OD>23.876</OD>
<ID>18.796</ID>
<Len>4.699</Len>
<FinishCode>0</FinishCode>
<UsageCode>0</UsageCode>
<AutoSize>0</AutoSize>
<AttachedParts>
</AttachedParts>
</Ring>
<CustomFinSet>
<PartMfg>LOC</PartMfg>
<KnownMass>0.</KnownMass>
<Density>724.996</Density>
<Material>Aircraft plywood (LOC)</Material>
<Name>L-ONE Striker</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>177.8</Xb>
<CalcMass>4.17008</CalcMass>
<CalcCG>42.3333</CalcCG>
<WettedSurface>0.00232258</WettedSurface>
<PaintedSurface>0.00696773</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>FS-1Xeno</PartNo>
<PartDesc>fins</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>6</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>8.39194</BarrowmanCNa>
<BarrowmanXN>0.324481</BarrowmanXN>
<RockSimCNa>13.035</RockSimCNa>
<RockSimXN>0.326803</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>292.1</Station>
<FinCount>3</FinCount>
<RootChord>50.8</RootChord>
<TipChord>22.52</TipChord>
<SemiSpan>30.48</SemiSpan>
<MidChordLen>48.7918</MidChordLen>
<SweepDistance>52.24</SweepDistance>
<Thickness>1.651</Thickness>
<ShapeCode>2</ShapeCode>
<FinishCode>0</FinishCode>
<TipShapeCode>0</TipShapeCode>
<TabLength>0.</TabLength>
<TabDepth>0.</TabDepth>
<TabOffset>0.</TabOffset>
<SweepMode>1</SweepMode>
<SweepAngle>0.</SweepAngle>
<RockSimXNPerFin>0.</RockSimXNPerFin>
<RockSimRadialXNPerFin>25.9806</RockSimRadialXNPerFin>
<RockSimCNaPerFin>7.52576</RockSimCNaPerFin>
<TaperRatio>0.443307</TaperRatio>
<CantAngle>0.</CantAngle>
<CantPivotPoint>0.</CantPivotPoint>
<AverageChord>38.23</AverageChord>
<EffectiveTipChord>22.5175</EffectiveTipChord>
<PointList>50.8,0|76.2,30.48|50.8,30.48|0,0|</PointList>
<AutoCalcGridStepX>0,0,0,0,0,0,0</AutoCalcGridStepX>
<GridStepCountX>10,10,10,10,10,10,10</GridStepCountX>
<UseAbsoluteGridStepsX>0,0,0,0,0,0,0</UseAbsoluteGridStepsX>
<GridStepSizeX>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeX>
<SnapToSizeX>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeX>
<AutoCalcGridStepY>0,0,0,0,0,0,0</AutoCalcGridStepY>
<GridStepCountY>10,10,10,10,10,10,10</GridStepCountY>
<UseAbsoluteGridStepsY>0,0,0,0,0,0,0</UseAbsoluteGridStepsY>
<GridStepSizeY>0.5,10,0.5,0.5,0.00018939,0.001,1</GridStepSizeY>
<SnapToSizeY>0.25,5,0.1,0.1,0.00018939,0.001,1</SnapToSizeY>
<AttachedParts>
</AttachedParts>
</CustomFinSet>
<Streamer>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>0.</KnownMass>
<Density>924.265</Density>
<Material>Polyethylene LDPE</Material>
<Name>Streamer</Name>
<KnownCG>0.</KnownCG>
<UseKnownCG>0</UseKnownCG>
<Xb>127.</Xb>
<CalcMass>0.237459</CalcMass>
<CalcCG>16.51</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>ST-6</PartNo>
<PartDesc>Streamer</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>7</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>241.3</Station>
<Len>152.4</Len>
<Width>33.02</Width>
<Thickness>0.051054</Thickness>
<StreamerCount>1</StreamerCount>
<DragCoefficient>0.362308</DragCoefficient>
<IsFolded>1</IsFolded>
<AutoCalcCd>1</AutoCalcCd>
<AttachedParts>
</AttachedParts>
</Streamer>
<MassObject>
<PartMfg>Estes</PartMfg>
<KnownMass>1.40047</KnownMass>
<Density>0.</Density>
<Name>Engine hook</Name>
<KnownCG>190.5</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>190.5</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>0</DensityType>
<PartNo>Engine hook</PartNo>
<PartDesc>Standard size</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>8</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>304.8</Station>
<TypeCode>0</TypeCode>
<Len>0.</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
<MassObject>
<PartMfg>LOC Precision</PartMfg>
<KnownMass>1.41748</KnownMass>
<Density>0.00402</Density>
<Material>1/4 In. flat elastic</Material>
<Name>Shock cord</Name>
<KnownCG>139.7</KnownCG>
<UseKnownCG>1</UseKnownCG>
<Xb>139.7</Xb>
<CalcMass>0.</CalcMass>
<CalcCG>0.</CalcCG>
<WettedSurface>0.</WettedSurface>
<PaintedSurface>0.</PaintedSurface>
<GlueJointLength>0.</GlueJointLength>
<DensityType>2</DensityType>
<PartNo>SCKV-6</PartNo>
<PartDesc>6' Kevlar Shock Cord</PartDesc>
<RadialLoc>0.</RadialLoc>
<RadialAngle>0.</RadialAngle>
<Texture>file=()|position=(0,0,0)|origin=(0.5,0.5,0.5)|scale=(1,1,1)|repeat=(1)|interpolate=(0)|flipr(0)|flips(0)|flipt=(0)|preventseam=(1)</Texture>
<Opacity>1.</Opacity>
<Specular>0.</Specular>
<SpecularPower>1.</SpecularPower>
<Ambient>0.</Ambient>
<Diffuse>1.</Diffuse>
<AbientColor>blue</AbientColor>
<DiffuseColor>blue</DiffuseColor>
<SpecularColor>white</SpecularColor>
<UseSingleColor>1</UseSingleColor>
<SerialNo>9</SerialNo>
<DisplayFlags>0</DisplayFlags>
<MetricsFlags>0</MetricsFlags>
<LocationMode>0</LocationMode>
<Color>blue</Color>
<BarrowmanCNa>0.</BarrowmanCNa>
<BarrowmanXN>0.</BarrowmanXN>
<RockSimCNa>0.</RockSimCNa>
<RockSimXN>0.</RockSimXN>
<SimpleColorModel>1</SimpleColorModel>
<ProduceTemplate>0</ProduceTemplate>
<TemplateUnits>8</TemplateUnits>
<Removed>0</Removed>
<Station>254.</Station>
<TypeCode>0</TypeCode>
<Len>1828.8</Len>
<AttachedParts>
</AttachedParts>
</MassObject>
</AttachedParts>
</BodyTube>
</Stage3Parts>
<Stage2Parts>
</Stage2Parts>
<Stage1Parts>
</Stage1Parts>
<SideViewDims>
</SideViewDims>
<BaseViewDims>
</BaseViewDims>
<VertViewDims>
</VertViewDims>
</RocketDesign>
</DesignInformation>
<SimulationResultsList>
<SimulationResults>
<MaxAltitude>458.953</MaxAltitude>
<MaxVelocity>123.154</MaxVelocity>
<MaxAcceleration>234.014</MaxAcceleration>
<TimeToApogee>9.0075</TimeToApogee>
<OptimalDelay>7.14625</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>1.86125</TimeToBurnout>
<TimeToLanding>20.8212</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>0.612942</MinLaunchGuideLen>
<MaxVertVelocity>123.149</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>234.014</MaxVertAcceleration>
<MaxHorzAcceleration>0.31126</MaxHorzAcceleration>
<MaxRange>8.69924</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>2</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[C6-None] </SimulationName>
<VelocityAtLaunchGuideEnd>17.8086</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.18875</TimeToFreeFlight>
<TimeToMaxVelocity>1.84</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.19125</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.124</ExecutionTime>
<RangeAtLanding>-8.69924</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>59.943</VelocityAtLanding>
<XVelcoityAtLanding>-0.13665</XVelcoityAtLanding>
<YVelocityAtLanding>-59.9429</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>58.7794</Mass0>
<CG0>243.323</CG0>
<LaterialMOI0>3965.58</LaterialMOI0>
<RadialMOI0>1.13533e-05</RadialMOI0>
<CP0>271.684</CP0>
<CNA0>10.3919</CNA0>
<SM0>1.11658</SM0>
<GUID>{29686032-aeb8-4f10-acea-094b7db0cb8b}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>7</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>C6</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Estes</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>3</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>77.736</MaxAltitude>
<MaxVelocity>38.0663</MaxVelocity>
<MaxAcceleration>180.935</MaxAcceleration>
<TimeToApogee>4.1625</TimeToApogee>
<OptimalDelay>3.43125</OptimalDelay>
<MultiDelayCount>1</MultiDelayCount>
<VelocityAtDeplyment>4.28332</VelocityAtDeplyment>
<AltitudeAtDeployment>76.8215</AltitudeAtDeployment>
<DelayTime>3</DelayTime>
<EjectTime>3.73</EjectTime>
<FinalState>0</FinalState>
<TimeToBurnout>0.73125</TimeToBurnout>
<TimeToLanding>9.36375</TimeToLanding>
<TimeToEject>3.73</TimeToEject>
<MinLaunchGuideLen>0.715011</MinLaunchGuideLen>
<MaxVertVelocity>38.0659</MaxVertVelocity>
<MaxHorzVelocity>0.241707</MaxHorzVelocity>
<MaxVertAcceleration>180.935</MaxVertAcceleration>
<MaxHorzAcceleration>0.0184504</MaxHorzAcceleration>
<MaxRange>0.609873</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>2</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[A8-3] </SimulationName>
<VelocityAtLaunchGuideEnd>15.9522</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.22375</TimeToFreeFlight>
<TimeToMaxVelocity>0.69625</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.22625</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.055</ExecutionTime>
<RangeAtLanding>0.609873</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>20.4122</VelocityAtLanding>
<XVelcoityAtLanding>0.241712</XVelcoityAtLanding>
<YVelocityAtLanding>-20.4108</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,3.73,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,3.73,0,0</TimeToDeployment>
<DeploymentType>32,32,83,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>52.0294</Mass0>
<CG0>234.88</CG0>
<LaterialMOI0>3323.47</LaterialMOI0>
<RadialMOI0>9.09876e-06</RadialMOI0>
<CP0>271.684</CP0>
<CNA0>10.3919</CNA0>
<SM0>1.44897</SM0>
<GUID>{6fde43ce-8a5b-44df-bf84-924310ad94b3}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>7</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>1</HasDeployed>
<DeployedAt_Altitude>76.8215</DeployedAt_Altitude>
<DeployedAt_Velocity>4.28332</DeployedAt_Velocity>
<DeployedAt_Range>-0.526469</DeployedAt_Range>
<DeployedAt_Time>3.73</DeployedAt_Time>
<DeviceID>256</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>A8</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Estes</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>3</MountSerialNo>
<EjectionDelay>3.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>859.77</MaxAltitude>
<MaxVelocity>222.077</MaxVelocity>
<MaxAcceleration>318.501</MaxAcceleration>
<TimeToApogee>10.7563</TimeToApogee>
<OptimalDelay>9.055</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>1.70125</TimeToBurnout>
<TimeToLanding>28.0587</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>0.300684</MinLaunchGuideLen>
<MaxVertVelocity>222.077</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>318.501</MaxVertAcceleration>
<MaxHorzAcceleration>0.0632277</MaxHorzAcceleration>
<MaxRange>1.5604</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>2</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[D13W-None] </SimulationName>
<VelocityAtLaunchGuideEnd>23.8421</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.08</TimeToFreeFlight>
<TimeToMaxVelocity>1.14625</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.17625</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.149</ExecutionTime>
<RangeAtLanding>-1.55921</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>70.249</VelocityAtLanding>
<XVelcoityAtLanding>-0.010325</XVelcoityAtLanding>
<YVelocityAtLanding>-70.249</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>68.6794</Mass0>
<CG0>252.704</CG0>
<LaterialMOI0>4908.23</LaterialMOI0>
<RadialMOI0>1.46599e-05</RadialMOI0>
<CP0>271.684</CP0>
<CNA0>10.3919</CNA0>
<SM0>0.747257</SM0>
<GUID>{6fc34393-ef54-410c-a845-6776f41de108}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>7</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>D13W</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>3</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>37.6434</MaxAltitude>
<MaxVelocity>24.5972</MaxVelocity>
<MaxAcceleration>51.6478</MaxAcceleration>
<TimeToApogee>3.8475</TimeToApogee>
<OptimalDelay>1.74625</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>2.10125</TimeToBurnout>
<TimeToLanding>6.76375</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>11.7471</MinLaunchGuideLen>
<MaxVertVelocity>17.8926</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>51.6478</MaxVertAcceleration>
<MaxHorzAcceleration>0.212981</MaxHorzAcceleration>
<MaxRange>5.96812</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>2</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[A3T-None] </SimulationName>
<VelocityAtLaunchGuideEnd>6.22229</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.365</TimeToFreeFlight>
<TimeToMaxVelocity>6.7625</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.1925</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.059</ExecutionTime>
<RangeAtLanding>-5.96812</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>24.6063</VelocityAtLanding>
<XVelcoityAtLanding>-0.913843</XVelcoityAtLanding>
<YVelocityAtLanding>-24.5893</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>44.6794</Mass0>
<CG0>224.297</CG0>
<LaterialMOI0>2661.62</LaterialMOI0>
<RadialMOI0>5.47028e-06</RadialMOI0>
<CP0>271.684</CP0>
<CNA0>10.3919</CNA0>
<SM0>1.86565</SM0>
<GUID>{6ca9c39e-e24c-4c80-9cbd-2e97b059b916}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>7</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>A3T</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Q</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>3</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>185.257</MaxAltitude>
<MaxVelocity>68.4909</MaxVelocity>
<MaxAcceleration>252.963</MaxAcceleration>
<TimeToApogee>6.025</TimeToApogee>
<OptimalDelay>5.11375</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>0.91125</TimeToBurnout>
<TimeToLanding>12.9088</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>0.768126</MinLaunchGuideLen>
<MaxVertVelocity>68.4741</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>252.96</MaxVertAcceleration>
<MaxHorzAcceleration>0.281155</MaxHorzAcceleration>
<MaxRange>7.35311</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>2</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[B4-None] </SimulationName>
<VelocityAtLaunchGuideEnd>15.5663</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.20375</TimeToFreeFlight>
<TimeToMaxVelocity>0.87875</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.2575</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.088</ExecutionTime>
<RangeAtLanding>-7.35285</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>46.7172</VelocityAtLanding>
<XVelcoityAtLanding>-0.476525</XVelcoityAtLanding>
<YVelocityAtLanding>-46.7147</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>52.2794</Mass0>
<CG0>235.232</CG0>
<LaterialMOI0>3347.23</LaterialMOI0>
<RadialMOI0>9.23356e-06</RadialMOI0>
<CP0>271.684</CP0>
<CNA0>10.3919</CNA0>
<SM0>1.43513</SM0>
<GUID>{3cedee62-e9a3-48c0-91a4-a5c180d3b5fa}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>7</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>B4</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Q</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>3</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
<SimulationResults>
<MaxAltitude>817.499</MaxAltitude>
<MaxVelocity>230.074</MaxVelocity>
<MaxAcceleration>374.591</MaxAcceleration>
<TimeToApogee>10.5</TimeToApogee>
<OptimalDelay>9.27875</OptimalDelay>
<MultiDelayCount>0</MultiDelayCount>
<FinalState>4</FinalState>
<TimeToBurnout>1.22125</TimeToBurnout>
<TimeToLanding>27.1637</TimeToLanding>
<TimeToEject>0.</TimeToEject>
<MinLaunchGuideLen>0.291306</MinLaunchGuideLen>
<MaxVertVelocity>230.041</MaxVertVelocity>
<MaxHorzVelocity>0.</MaxHorzVelocity>
<MaxVertAcceleration>374.591</MaxVertAcceleration>
<MaxHorzAcceleration>1.41846</MaxHorzAcceleration>
<MaxRange>20.7663</MaxRange>
<LaunchStartVelocity>0.</LaunchStartVelocity>
<LaunchStartRollRate>0.</LaunchStartRollRate>
<LaunchGuideType>0</LaunchGuideType>
<LaunchGuideLen>914.4</LaunchGuideLen>
<LaunchWindDirection>0</LaunchWindDirection>
<LaunchWindSpeed>0.</LaunchWindSpeed>
<LaunchDirection>0</LaunchDirection>
<LaunchAngle>0.</LaunchAngle>
<LaunchGuideAzimuth>0.</LaunchGuideAzimuth>
<LaunchGuideElevation>0.</LaunchGuideElevation>
<LaunchBarometer>759.813</LaunchBarometer>
<LaunchLatitude>0.</LaunchLatitude>
<LaunchLongitude>0.</LaunchLongitude>
<LaunchHumidity>50.</LaunchHumidity>
<LaunchTemperature>15.</LaunchTemperature>
<LaunchAltitude>0.</LaunchAltitude>
<LaunchLandingAltitude>0.</LaunchLandingAltitude>
<CompStateMask>0</CompStateMask>
<LaunchWindPreset>2</LaunchWindPreset>
<LaunchWindLowSpeed>0.</LaunchWindLowSpeed>
<LaunchWindHighSpeed>0.89408</LaunchWindHighSpeed>
<LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
<LaunchWindFrequency>0.01</LaunchWindFrequency>
<LaunchWindDeltaFrequency>0.02</LaunchWindDeltaFrequency>
<LaunchUseRandomConditions>0</LaunchUseRandomConditions>
<LaunchCloudCoverPreset>5</LaunchCloudCoverPreset>
<LaunchCCLow>0.</LaunchCCLow>
<LaunchCCHigh>0.1</LaunchCCHigh>
<LaunchThermalPosPreset>1</LaunchThermalPosPreset>
<LaunchThermalPos>0.</LaunchThermalPos>
<LaunchMultipleThermals>0</LaunchMultipleThermals>
<LaunchMaxThermals>3</LaunchMaxThermals>
<LaunchThermalDia>300.</LaunchThermalDia>
<LaunchThermalHeight>2000.</LaunchThermalHeight>
<LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
<LaunchThermalSpeed>5.99999</LaunchThermalSpeed>
<LaunchWindTableSize>0</LaunchWindTableSize>
<LaunchWindAltTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindAltTable>
<LaunchWindSpeedTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindSpeedTable>
<LaunchWindDirectionTable>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0</LaunchWindDirectionTable>
<LaunchLossPreset>2</LaunchLossPreset>
<LaunchLossPercent>0.99</LaunchLossPercent>
<LaunchSiteDia>2000.</LaunchSiteDia>
<LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
<LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
<LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
<LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
<LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
<LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
<LaunchVariableIgnitionDelaySec>0.08</LaunchVariableIgnitionDelaySec>
<LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
<LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
<LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
<LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
<LaunchTrackLossPreset>1</LaunchTrackLossPreset>
<LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
<CNaMultiplier>1.</CNaMultiplier>
<CdMultiplier>1.</CdMultiplier>
<CPOffset>0.</CPOffset>
<SaveSimAsText>0</SaveSimAsText>
<OutputAtMaxRes>0</OutputAtMaxRes>
<MaxSimTim>3600.</MaxSimTim>
<MassUncertainty>0.</MassUncertainty>
<MOIUncertainty>0.</MOIUncertainty>
<CGUncertainty>0.</CGUncertainty>
<CdUncertainty>0.</CdUncertainty>
<CnaUncertainty>0.</CnaUncertainty>
<CPUncertainty>0.</CPUncertainty>
<FinCantUncertainty>0.</FinCantUncertainty>
<TotImpulseUncertainty>0.</TotImpulseUncertainty>
<PropellantUncertainty>0.</PropellantUncertainty>
<ThrustAxisUncertainty>0.</ThrustAxisUncertainty>
<WindDirectionUncertainty>0.</WindDirectionUncertainty>
<WindVelocityUncertainty>0.</WindVelocityUncertainty>
<LaunchGuideAzimuthUncertainty>0.</LaunchGuideAzimuthUncertainty>
<LaunchGuideElevationUncertainty>0.</LaunchGuideElevationUncertainty>
<IgnitionUncertainty>0.</IgnitionUncertainty>
<CATOUncertainty>0.</CATOUncertainty>
<DeploymentUncertainty>0.</DeploymentUncertainty>
<RecoveryDeviceUncertainty>0.</RecoveryDeviceUncertainty>
<SimulationName>[D24T-None] </SimulationName>
<VelocityAtLaunchGuideEnd>24.3361</VelocityAtLaunchGuideEnd>
<WindStartAltitude>0.</WindStartAltitude>
<TimeToWindShear>0.</TimeToWindShear>
<TimeToFreeFlight>0.085</TimeToFreeFlight>
<TimeToMaxVelocity>1.015</TimeToMaxVelocity>
<TimeToMaxAcceleration>0.04125</TimeToMaxAcceleration>
<Nsims>10</Nsims>
<CalcResolution>1</CalcResolution>
<SamplesPerSecond>800.</SamplesPerSecond>
<SimulationType>0</SimulationType>
<LocationDataServerName>Earth</LocationDataServerName>
<LocationDataServerDisplayName>Standard earth condistions.</LocationDataServerDisplayName>
<ExecutionTime>0.15</ExecutionTime>
<RangeAtLanding>-19.5453</RangeAtLanding>
<DirectionAtLanding>0.</DirectionAtLanding>
<VelocityAtLanding>69.3883</VelocityAtLanding>
<XVelcoityAtLanding>-0.200663</XVelcoityAtLanding>
<YVelocityAtLanding>-69.388</YVelocityAtLanding>
<ZVelocityAtLanding>0.</ZVelocityAtLanding>
<StageSeparationTime>0,0,0,0,0</StageSeparationTime>
<StageEjectTime>-1,-1,-1,-1,-1</StageEjectTime>
<TimeToDeployment>0,0,0,0,0</TimeToDeployment>
<DeploymentType>32,32,32,32,32</DeploymentType>
<SamplesPerSecondDescent>1.</SamplesPerSecondDescent>
<CalculationFlags>1</CalculationFlags>
<Mass0>66.4794</Mass0>
<CG0>250.861</CG0>
<LaterialMOI0>4698.71</LaterialMOI0>
<RadialMOI0>1.39251e-05</RadialMOI0>
<CP0>271.684</CP0>
<CNA0>10.3919</CNA0>
<SM0>0.819823</SM0>
<GUID>{7b2b86e5-157f-4f92-b45f-b44c8b9611d3}</GUID>
<Booster1Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster1Staging>
<Booster2Staging>
<SimulationEvent>
<PartSerialNo>0</PartSerialNo>
<Type>0</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>0,0,0</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</Booster2Staging>
<SimulationEvents>
<SimulationEvent>
<PartSerialNo>7</PartSerialNo>
<Type>1</Type>
<DeployAltitude>0.</DeployAltitude>
<DeplyTime>0.</DeplyTime>
<HasDeployed>0</HasDeployed>
<DeployedAt_Altitude>0.</DeployedAt_Altitude>
<DeployedAt_Velocity>0.</DeployedAt_Velocity>
<DeployedAt_Range>0.</DeployedAt_Range>
<DeployedAt_Time>0.</DeployedAt_Time>
<DeviceID>-1</DeviceID>
<TestType>28,28,28</TestType>
<TestCondition>0,0,0</TestCondition>
<TestValueAltitude>0,0,0</TestValueAltitude>
<TestValueDegrees>0,0,0</TestValueDegrees>
<TestValuePressure>0,0,0</TestValuePressure>
<TestValueMach>0,0,0</TestValueMach>
<TestValueTime>0,0,0</TestValueTime>
<TestValueQ>0,0,0</TestValueQ>
</SimulationEvent>
</SimulationEvents>
<Stage1Engines>
</Stage1Engines>
<Stage2Engines>
</Stage2Engines>
<Stage3Engines>
<EngineSet>
<EngineCount>1</EngineCount>
<EngineCode>D24T</EngineCode>
<IgnitionDelay>0.</IgnitionDelay>
<EngineMfg>Aerotech</EngineMfg>
<EngineOverhang>0.50038</EngineOverhang>
<CasingCG>0.</CasingCG>
<MountSerialNo>3</MountSerialNo>
<EjectionDelay>-2.</EjectionDelay>
<RotateXaboutY>0.</RotateXaboutY>
<RotateEngineAxisAboutX>0.</RotateEngineAxisAboutX>
</EngineSet>
</Stage3Engines>
<DropItems>
</DropItems>
</SimulationResults>
</SimulationResultsList>
</RockSimDocument>
