<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>12</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>261.33586357452555</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>10.9996</KnownMass>
                    <Density>1049.21</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>72.9996</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>6.028835199065108</CalcMass>
                    <CalcCG>72.9996</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>76.2</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.00076</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>25.4</BaseDia>
                    <ShoulderLen>25.4</ShoulderLen>
                    <ShoulderOD>24.384</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>9.849442199842056</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>88.9</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>9.849442199842056</CalcMass>
                    <CalcCG>88.9</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>177.8</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>25.4</OD>
                    <ID>24.13</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>24.13</MotorDia>
                    <EngineOverhang>0.5</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>3.96893</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>120.65</Xb>
                            <CalcMass>3.697329071940707</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>24.13</OD>
                            <ID>22.352</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>0.9017924008928966</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>1.58496</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>168.275</Xb>
                            <CalcMass>0.9017924008928966</CalcMass>
                            <CalcCG>1.58496</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>3.16992</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>22.352</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>12.663568542654073</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>114.3</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>12.663568542654073</CalcMass>
                    <CalcCG>114.3</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>228.6</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>25.4</OD>
                    <ID>24.13</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>24.13</MotorDia>
                    <EngineOverhang>0.5</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>1.1747173554097277</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Body tube</Name>
                            <KnownCG>34.925</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>158.75</Xb>
                            <CalcMass>1.1747173554097277</CalcMass>
                            <CalcCG>34.925</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>69.85</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>19.05</OD>
                            <ID>18.542</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>18.542</MotorDia>
                            <EngineOverhang>0.50038</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>0.5800128929376103</KnownMass>
                                    <Density>724.996</Density>
                                    <Material>Aircraft plywood (LOC)</Material>
                                    <Name>Centering ring</Name>
                                    <KnownCG>2.3495</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>0.0</Xb>
                                    <CalcMass>0.5800128929376103</CalcMass>
                                    <CalcCG>2.3495</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>4.699</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>7</SerialNo>
                                    <OD>23.876</OD>
                                    <ID>18.796</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <BodyTube>
                                    <KnownMass>0.642890770869691</KnownMass>
                                    <Density>1121.29</Density>
                                    <Material>Paper</Material>
                                    <Name>Thrust ring</Name>
                                    <KnownCG>2.3495</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>0.0</Xb>
                                    <CalcMass>0.642890770869691</CalcMass>
                                    <CalcCG>2.3495</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>4.699</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>8</SerialNo>
                                    <OD>17.8308</OD>
                                    <ID>12.7508</ID>
                                    <IsMotorMount>0</IsMotorMount>
                                    <MotorDia>12.7508</MotorDia>
                                    <EngineOverhang>0.5</EngineOverhang>
                                    <IsInsideTube>1</IsInsideTube>
                                    <AttachedParts/>
                                </BodyTube>
                            </AttachedParts>
                        </BodyTube>
                        <Ring>
                            <KnownMass>0.5800128929376103</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>2.3495</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>222.25</Xb>
                            <CalcMass>0.5800128929376103</CalcMass>
                            <CalcCG>2.3495</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>4.699</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>23.876</OD>
                            <ID>18.796</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <CustomFinSet>
                            <KnownMass>6.288158375271002</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Hi-Tech</Name>
                            <KnownCG>26.864219665271968</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>171.45</Xb>
                            <CalcMass>6.288158375271002</CalcMass>
                            <CalcCG>26.864219665271968</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>1.5</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>31.75</TabLength>
                            <TabDepth>3.175</TabDepth>
                            <TabOffset>19.05</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>50.80000000000001,0.0|40.64,47.625|14.732,47.625|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Streamer>
                            <KnownMass>0.18266063587799763</KnownMass>
                            <Density>0.004718742531000001</Density>
                            <Material>Polyethylene LDPE</Material>
                            <Name>Streamer</Name>
                            <KnownCG>12.5</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>25.4</Xb>
                            <CalcMass>0.18266063587799763</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <Width>25.4</Width>
                            <DragCoefficient>0.381</DragCoefficient>
                        </Streamer>
                        <MassObject>
                            <KnownMass>2.83495</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>76.2</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>76.2</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>18.288</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>