<RockSimDocument>
 <FileVersion>2</FileVersion>
 <DesignInformation>
  <RocketDesign>
   <Name>PK-68 Minie Magg</Name>
   <CalculateCD>1</CalculateCD>
   <FixedCd>0.75</FixedCd>
   <FixedCd2>0.78</FixedCd2>
   <FixedCd3>0.8</FixedCd3>
   <StageCount>1</StageCount>
   <Stage3Mass>0.</Stage3Mass>
   <Stage2Mass>0.</Stage2Mass>
   <Stage1Mass>0.</Stage1Mass>
   <Stage321CG>0.</Stage321CG>
   <Stage32CG>0.</Stage32CG>
   <Stage3CG>0.</Stage3CG>
   <CPCalcFlags>5</CPCalcFlags>
   <LaunchGuideLength>1828.80001810512</LaunchGuideLength>
   <UseKnownMass>0</UseKnownMass>
   <DefaultFinish>1</DefaultFinish>
   <FinishMedium>0</FinishMedium>
   <FinishCoatCount>2</FinishCoatCount>
   <GlueType>0</GlueType>
   <Comments></Comments>
   <Designer>LOC Precision</Designer>
   <CPSimFlags>4</CPSimFlags>
   <LastSerialNumber>27</LastSerialNumber>
   <DisplayFlags>1</DisplayFlags>
   <MetricsFlags>0</MetricsFlags>
   <CameraState></CameraState>
   <BarromanXN>0.,629.25984896567,343.725683914181,0.</BarromanXN>
   <BarrowmanCNa>0.,7.12493867472325,16.8976358889834,0.</BarrowmanCNa>
   <RockSimXN>0.,694.924612880004,355.367999346391,0.</RockSimXN>
   <RockSimCNa>0.,9.79101373926535,25.1086068568132,0.</RockSimCNa>
   <ViewType>0</ViewType>
   <ViewStageCount>1</ViewStageCount>
   <ViewTypeEdit>0</ViewTypeEdit>
   <ViewStageCountEdit>0</ViewStageCountEdit>
   <ZoomFactor>0.</ZoomFactor>
   <ZoomFactorEdit>0.</ZoomFactorEdit>
   <ScrollPosX>0</ScrollPosX>
   <ScrollPosY>0</ScrollPosY>
   <ScrollPosXEdit>0</ScrollPosXEdit>
   <ScrollPosYEdit>0</ScrollPosYEdit>
   <ThreeDFlags>0</ThreeDFlags>
   <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
   <SimulationEventList>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>0</HasDeployed>
     <DeployedAt_Altitude>0.</DeployedAt_Altitude>
     <DeployedAt_Velocity>0.</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>0.</DeployedAt_Time>
     <DeviceID>-1</DeviceID>
    </SimulationEvent>
   </SimulationEventList>
   <Stage3Parts>
    <NoseCone>
     <PartMfg>LOC Precision</PartMfg>
     <KnownMass>283.49523</KnownMass>
     <Density>1049.2093265</Density>
     <Material>Polystyrene PS</Material>
     <Name>Nose cone</Name>
     <KnownCG>215.9</KnownCG>
     <UseKnownCG>1</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>504.979359670757</CalcMass>
     <CalcCG>274.645927893397</CalcCG>
     <WettedSurface>9.90341604863845e-002</WettedSurface>
     <PaintedSurface>9.90341604863845e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC PNC-5.38</PartNo>
     <PartDesc>Plastic nose cone</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>1</SerialNo>
     <DisplayFlags>1</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>2.</BarrowmanCNa>
     <BarrowmanXN>0.151858283169651</BarrowmanXN>
     <RockSimCNa>2.</RockSimCNa>
     <RockSimXN>0.151858283169651</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <Len>330.2</Len>
     <BaseDia>139.7</BaseDia>
     <FinishCode>1</FinishCode>
     <ShapeCode>1</ShapeCode>
     <ConstructionType>1</ConstructionType>
     <ShoulderLen>101.6</ShoulderLen>
     <WallThickness>3.175</WallThickness>
     <ShapeParameter>0.</ShapeParameter>
     <ShoulderOD>136.525</ShoulderOD>
     <PointList></PointList>
     <BaseExtensionLen>0.</BaseExtensionLen>
     <CoreDia>0.</CoreDia>
     <CoreLen>0.</CoreLen>
     <AttachedParts>
      <MassObject>
       <PartMfg>Custom</PartMfg>
       <KnownMass>340.194276</KnownMass>
       <Density>0.</Density>
       <Material></Material>
       <Name>Ballast</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>57.15</Xb>
       <CalcMass>0.</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>14</SerialNo>
       <DisplayFlags>8</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>0</TypeCode>
       <Len>0.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
     </AttachedParts>
    </NoseCone>
    <BodyTube>
     <PartMfg>LOC/Precision</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>1121.29241</Density>
     <Material>Paper</Material>
     <Name>Body tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>605.151029491775</CalcMass>
     <CalcCG>304.8</CalcCG>
     <WettedSurface>0.269487305718401</WettedSurface>
     <PaintedSurface>0.269487305718401</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>LOC BT-5.38</PartNo>
     <PartDesc>Airframe tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>2</SerialNo>
     <DisplayFlags>1</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <SimpleColorModel>1</SimpleColorModel>
     <OD>140.716</OD>
     <ID>136.652</ID>
     <Len>609.6</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>0.</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <BodyTube>
       <PartMfg>LOC/Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1121.29241</Density>
       <Material>Paper</Material>
       <Name>MMT-38mm</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>0.</Xb>
       <CalcMass>50.1637138114656</CalcMass>
       <CalcCG>127.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC MMT-1.52</PartNo>
       <PartDesc>Motor mount tube</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>3</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>2</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>41.529</OD>
       <ID>38.735</ID>
       <Len>254.</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>1</IsMotorMount>
       <MotorDia>38.</MotorDia>
       <EngineOverhang>0.</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>0</IsInsideTube>
       <AttachedParts>
       </AttachedParts>
      </BodyTube>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>361.95</Xb>
       <CalcMass>46.0854433659218</CalcMass>
       <CalcCG>2.3876</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC CR-5.38-1.52</PartNo>
       <PartDesc>Centering Ring</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>4</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>136.652</OD>
       <ID>41.529</ID>
       <Len>4.7752</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>609.6</Xb>
       <CalcMass>46.0854433659218</CalcMass>
       <CalcCG>2.3876</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC CR-5.38-1.52</PartNo>
       <PartDesc>Centering Ring</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>8</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>136.652</OD>
       <ID>41.529</ID>
       <Len>4.7752</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <MassObject>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>7.08738075</KnownMass>
       <Density>1.02e-003</Density>
       <Material>1/16 In. braided nylon</Material>
       <Name>Shock cord mount</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>327.025</Xb>
       <CalcMass>0.51816</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>2</DensityType>
       <PartNo>SCM-3</PartNo>
       <PartDesc>Shock cord mount</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>9</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>1</TypeCode>
       <Len>508.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
      <MassObject>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1.2277353539e-002</Density>
       <Material>3/4 In. flat elastic</Material>
       <Name>Shock cord</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>298.45</Xb>
       <CalcMass>56.132060380308</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>2</DensityType>
       <PartNo>SC-750</PartNo>
       <PartDesc>3/4 In Elastic shock cord</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>10</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>1</TypeCode>
       <Len>4572.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
      <Parachute>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>85.048569</KnownMass>
       <Density>0.</Density>
       <Material>Rip stop nylon</Material>
       <Name>Parachute</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>117.475</Xb>
       <CalcMass>9.32688</CalcMass>
       <CalcCG>76.2</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LP-36</PartNo>
       <PartDesc>36 In. 10 lines</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>11</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <Dia>914.4</Dia>
       <SpillHoleDia>0.</SpillHoleDia>
       <SideCount>10</SideCount>
       <ShroudLineCount>10</ShroudLineCount>
       <Thickness>5.08e-002</Thickness>
       <ShroudLineLen>914.4</ShroudLineLen>
       <ChuteCount>1</ChuteCount>
       <ShroudLineMassPerMM>1.02e-003</ShroudLineMassPerMM>
       <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
       <DragCoefficient>0.75</DragCoefficient>
       <AttachedParts>
       </AttachedParts>
      </Parachute>
      <LaunchLug>
       <PartMfg>LOC</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1121.29241</Density>
       <Material>Paper</Material>
       <Name>Launch lug</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>400.05</Xb>
       <CalcMass>6.07852596587723</CalcMass>
       <CalcCG>76.2</CalcCG>
       <WettedSurface>1.42639168799529e-002</WettedSurface>
       <PaintedSurface>7.47900239245562e-003</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>LOC LL50</PartNo>
       <PartDesc>LL-50</PartDesc>
       <RadialLoc>78.1685</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>12</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <OD>15.621</OD>
       <ID>14.097</ID>
       <Len>152.4</Len>
       <FinishCode>1</FinishCode>
       <AttachedParts>
       </AttachedParts>
      </LaunchLug>
      <CustomFinSet>
       <PartMfg>LOC Precision</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>724.99563538</Density>
       <Material>Aircraft plywood (Birch)</Material>
       <Name>Custom Fin set</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>355.6</Xb>
       <CalcMass>119.315991144441</CalcMass>
       <CalcCG>169.37038117464</CalcCG>
       <WettedSurface>3.38305775e-002</WettedSurface>
       <PaintedSurface>0.1014917325</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>FS-68</PartNo>
       <PartDesc>Fin set</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>13</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>5.12493867472325</BarrowmanCNa>
       <BarrowmanXN>0.815565128344179</BarrowmanXN>
       <RockSimCNa>7.79101373926535</RockSimCNa>
       <RockSimXN>0.834333</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <FinCount>3</FinCount>
       <RootChord>260.35</RootChord>
       <TipChord>80.79</TipChord>
       <SemiSpan>120.65</SemiSpan>
       <MidChordLen>164.615256279605</MidChordLen>
       <SweepDistance>201.77</SweepDistance>
       <Thickness>3.175</Thickness>
       <ShapeCode>2</ShapeCode>
       <FinishCode>1</FinishCode>
       <TipShapeCode>1</TipShapeCode>
       <TabLength>114.3</TabLength>
       <TabDepth>3.175</TabDepth>
       <TabOffset>120.65</TabOffset>
       <SweepMode>0</SweepMode>
       <SweepAngle>0.</SweepAngle>
       <AverageChord>141.5</AverageChord>
       <EffectiveTipChord>80.7918012124121</EffectiveTipChord>
       <PointList>260.35,0.|260.35,76.2|228.6,120.65|0.,0.</PointList>
       <AttachedParts>
       </AttachedParts>
      </CustomFinSet>
      <MassObject>
       <PartMfg>Custom</PartMfg>
       <KnownMass>113.398092</KnownMass>
       <Density>0.</Density>
       <Material></Material>
       <Name><![CDATA[Paint & Glue]]></Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>1</UseKnownCG>
       <Xb>149.225</Xb>
       <CalcMass>0.</CalcMass>
       <CalcCG>0.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>15</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <SimpleColorModel>1</SimpleColorModel>
       <TypeCode>0</TypeCode>
       <Len>0.</Len>
       <AttachedParts>
       </AttachedParts>
      </MassObject>
     </AttachedParts>
    </BodyTube>
   </Stage3Parts>
   <Stage2Parts>
   </Stage2Parts>
   <Stage1Parts>
   </Stage1Parts>
  </RocketDesign>
 </DesignInformation>
 <SimulationResultsList>
  <SimulationResults>
   <MaxAltitude>333.040870186349</MaxAltitude>
   <MaxVelocity>74.2733963291102</MaxVelocity>
   <MaxAcceleration>57.830838525122</MaxAcceleration>
   <TimeToApogee>8.76800000000058</TimeToApogee>
   <OptimalDelay>6.16700000000075</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>4.39988941540575,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>332.899106659471,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>6.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>8.60000000000067,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.60099999999982</TimeToBurnout>
   <TimeToLanding>48.9559999999766</TimeToLanding>
   <TimeToEject>8.60000000000067</TimeToEject>
   <MinLaunchGuideLen>1.82553642269156</MinLaunchGuideLen>
   <MaxVertVelocity>74.1020361462014</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>57.830838525122</MaxVertAcceleration>
   <MaxHorzAcceleration>2.4293634381161</MaxHorzAcceleration>
   <MaxRange>244.812987665819</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H123W-6   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>13.4739330755087</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.782000000000001</TimeToWindShear>
   <TimeToFreeFlight>0.262</TimeToFreeFlight>
   <TimeToMaxVelocity>2.29099999999986</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>1.56148527464423</ExecutionTime>
   <RangeAtLanding>244.812987665819</RangeAtLanding>
   <VelocityAtLanding>8.99522894928321</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.34702797467594</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,8.60000000000067</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>332.899106659471</DeployedAt_Altitude>
     <DeployedAt_Velocity>4.39988941540575</DeployedAt_Velocity>
     <DeployedAt_Range>-24.288257904311</DeployedAt_Range>
     <DeployedAt_Time>8.60000000000067</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>H123W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>6.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>588.005561080892</MaxAltitude>
   <MaxVelocity>124.878836215309</MaxVelocity>
   <MaxAcceleration>104.187139562158</MaxAcceleration>
   <TimeToApogee>9.39600000000023</TimeToApogee>
   <OptimalDelay>7.09500000000037</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>26.8243091344749,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>579.1960948617,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>6.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>8.30000000000084,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>2.30099999999986</TimeToBurnout>
   <TimeToLanding>78.967000000013</TimeToLanding>
   <TimeToEject>8.30000000000084</TimeToEject>
   <MinLaunchGuideLen>1.0305600724038</MinLaunchGuideLen>
   <MaxVertVelocity>124.719371938115</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>95.7474969055185</MaxVertAcceleration>
   <MaxHorzAcceleration>14.0807021599821</MaxHorzAcceleration>
   <MaxRange>438.72294628211</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I161W-6   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>17.9334604176374</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.637</TimeToWindShear>
   <TimeToFreeFlight>0.25</TimeToFreeFlight>
   <TimeToMaxVelocity>2.01499999999989</TimeToMaxVelocity>
   <TimeToMaxAcceleration>8.30100000000084</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>5.80052045793594</ExecutionTime>
   <RangeAtLanding>438.72294628211</RangeAtLanding>
   <VelocityAtLanding>9.05355651934098</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.40985242491814</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,8.30000000000084</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>579.1960948617</DeployedAt_Altitude>
     <DeployedAt_Velocity>26.8243091344749</DeployedAt_Velocity>
     <DeployedAt_Range>-27.6683859451131</DeployedAt_Range>
     <DeployedAt_Time>8.30000000000084</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I161W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>6.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>809.678763282227</MaxAltitude>
   <MaxVelocity>161.019164060302</MaxVelocity>
   <MaxAcceleration>163.027312429152</MaxAcceleration>
   <TimeToApogee>11.9169999999988</TimeToApogee>
   <OptimalDelay>9.71599999999897</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>4.49440304530452,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>809.281909854525,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>10.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>12.2009999999987,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.20099999999987</TimeToBurnout>
   <TimeToLanding>106.301000000144</TimeToLanding>
   <TimeToEject>12.2009999999987</TimeToEject>
   <MinLaunchGuideLen>0.669547037647713</MinLaunchGuideLen>
   <MaxVertVelocity>160.867899137934</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>163.027312429152</MaxVertAcceleration>
   <MaxHorzAcceleration>1.24494650369914</MaxHorzAcceleration>
   <MaxRange>594.247705416735</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I211W-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>21.4871086426024</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.49</TimeToWindShear>
   <TimeToFreeFlight>0.161</TimeToFreeFlight>
   <TimeToMaxVelocity>1.86299999999991</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>9.82634053537605</ExecutionTime>
   <RangeAtLanding>594.247705416735</RangeAtLanding>
   <VelocityAtLanding>9.11151055440595</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.47221085331634</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,12.2009999999987</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>809.281909854525</DeployedAt_Altitude>
     <DeployedAt_Velocity>4.49440304530452</DeployedAt_Velocity>
     <DeployedAt_Range>-36.7492545844474</DeployedAt_Range>
     <DeployedAt_Time>12.2009999999987</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I211W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>980.706877336974</MaxAltitude>
   <MaxVelocity>202.419542172916</MaxVelocity>
   <MaxAcceleration>200.170244941442</MaxAcceleration>
   <TimeToApogee>12.4109999999986</TimeToApogee>
   <OptimalDelay>10.6099999999986</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>7.91616610395458,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>978.680016496657,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>10.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>11.8009999999989,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.80099999999991</TimeToBurnout>
   <TimeToLanding>125.342000000234</TimeToLanding>
   <TimeToEject>11.8009999999989</TimeToEject>
   <MinLaunchGuideLen>0.492525470098258</MinLaunchGuideLen>
   <MaxVertVelocity>202.299346119367</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>200.170244941442</MaxVertAcceleration>
   <MaxHorzAcceleration>2.9233703087435</MaxHorzAcceleration>
   <MaxRange>725.057406892989</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I284W-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>25.1499797757943</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.415</TimeToWindShear>
   <TimeToFreeFlight>0.14</TimeToFreeFlight>
   <TimeToMaxVelocity>1.56599999999994</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>12.0316842387569</ExecutionTime>
   <RangeAtLanding>725.057406892989</RangeAtLanding>
   <VelocityAtLanding>9.16909769083761</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.53411299574382</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,11.8009999999989</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>978.680016496657</DeployedAt_Altitude>
     <DeployedAt_Velocity>7.91616610395458</DeployedAt_Velocity>
     <DeployedAt_Range>-31.8682485844881</DeployedAt_Range>
     <DeployedAt_Time>11.8009999999989</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I284W</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>987.081719652668</MaxAltitude>
   <MaxVelocity>200.31435808082</MaxVelocity>
   <MaxAcceleration>134.206455309596</MaxAcceleration>
   <TimeToApogee>12.7039999999984</TimeToApogee>
   <OptimalDelay>10.4319999999985</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>6.10971704805104,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>986.099179834036,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>10.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>12.2719999999986,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.27199999999986</TimeToBurnout>
   <TimeToLanding>127.094000000243</TimeToLanding>
   <TimeToEject>12.2719999999986</TimeToEject>
   <MinLaunchGuideLen>0.744840360312545</MinLaunchGuideLen>
   <MaxVertVelocity>200.125535809161</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>133.724042288247</MaxVertAcceleration>
   <MaxHorzAcceleration>2.85846890860754</MaxHorzAcceleration>
   <MaxRange>722.434336578285</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I240-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>21.679648615778</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.515</TimeToWindShear>
   <TimeToFreeFlight>0.198</TimeToFreeFlight>
   <TimeToMaxVelocity>1.83599999999991</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.667</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>10.8056940277242</ExecutionTime>
   <RangeAtLanding>722.434336578285</RangeAtLanding>
   <VelocityAtLanding>9.11674363411672</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.47783856004629</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,12.2719999999986</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>986.099179834036</DeployedAt_Altitude>
     <DeployedAt_Velocity>6.10971704805104</DeployedAt_Velocity>
     <DeployedAt_Range>-44.0136600550205</DeployedAt_Range>
     <DeployedAt_Time>12.2719999999986</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I240</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>CSR</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>804.109512766234</MaxAltitude>
   <MaxVelocity>172.434024616499</MaxVelocity>
   <MaxAcceleration>205.707923809746</MaxAcceleration>
   <TimeToApogee>11.638999999999</TimeToApogee>
   <OptimalDelay>10.0379999999991</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>2.74432142003839,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>804.102808061723,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>10.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>11.600999999999,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.60099999999993</TimeToBurnout>
   <TimeToLanding>105.57100000014</TimeToLanding>
   <TimeToEject>11.600999999999</TimeToEject>
   <MinLaunchGuideLen>0.492060004219438</MinLaunchGuideLen>
   <MaxVertVelocity>172.341297015309</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>205.707923809746</MaxVertAcceleration>
   <MaxHorzAcceleration>1.11304398498263</MaxHorzAcceleration>
   <MaxRange>605.108529607769</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I300T-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>25.5499207679599</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.417</TimeToWindShear>
   <TimeToFreeFlight>0.139</TimeToFreeFlight>
   <TimeToMaxVelocity>1.36699999999996</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>9.88868653514139</ExecutionTime>
   <RangeAtLanding>605.108529607769</RangeAtLanding>
   <VelocityAtLanding>9.09675493468573</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.45633978159163</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,11.600999999999</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>804.102808061723</DeployedAt_Altitude>
     <DeployedAt_Velocity>2.74432142003839</DeployedAt_Velocity>
     <DeployedAt_Range>-24.7307004653154</DeployedAt_Range>
     <DeployedAt_Time>11.600999999999</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I300T</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>A-RMS</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>632.134432732706</MaxAltitude>
   <MaxVelocity>145.148127364417</MaxVelocity>
   <MaxAcceleration>210.035326078812</MaxAcceleration>
   <TimeToApogee>10.4999999999996</TimeToApogee>
   <OptimalDelay>9.39899999999963</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>6.10938874990822,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>630.369375553659,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>10.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>11.1009999999993,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>1.10099999999999</TimeToBurnout>
   <TimeToLanding>85.1150000000424</TimeToLanding>
   <TimeToEject>11.1009999999993</TimeToEject>
   <MinLaunchGuideLen>0.465804105185955</MinLaunchGuideLen>
   <MaxVertVelocity>145.106724292895</MaxVertVelocity>
   <MaxHorzVelocity>3.3528</MaxHorzVelocity>
   <MaxVertAcceleration>210.035326078812</MaxVertAcceleration>
   <MaxHorzAcceleration>0.616814362710113</MaxHorzAcceleration>
   <MaxRange>485.084338180217</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>3.3528</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>45.0000008347611</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>21.1111111111111</LaunchTemperature>
   <LaunchAltitude>182.88</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I357T-10  ] </SimulationName>
   <VelocityAtLaunchGuideEnd>26.3795624217642</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>15.24</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.401</TimeToWindShear>
   <TimeToFreeFlight>0.136</TimeToFreeFlight>
   <TimeToMaxVelocity>0.993000000000001</TimeToMaxVelocity>
   <TimeToMaxAcceleration>1.e-003</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>7.6442858579594</ExecutionTime>
   <RangeAtLanding>485.084338180217</RangeAtLanding>
   <VelocityAtLanding>9.05355545255732</VelocityAtLanding>
   <XVelcoityAtLanding>3.3528</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.40985127648108</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,11.1009999999993</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>1</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>630.369375553659</DeployedAt_Altitude>
     <DeployedAt_Velocity>6.10938874990822</DeployedAt_Velocity>
     <DeployedAt_Range>-11.2239402204492</DeployedAt_Range>
     <DeployedAt_Time>11.1009999999993</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I357T</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>AEROT</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>800.151715535479</MaxAltitude>
   <MaxVelocity>160.101413143608</MaxVelocity>
   <MaxAcceleration>97.1432437541713</MaxAcceleration>
   <TimeToApogee>12.0799999999998</TimeToApogee>
   <OptimalDelay>9.73999999999979</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>148.379195476574,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>229.354574451824,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>2.33999999999999,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.33999999999999</TimeToBurnout>
   <TimeToLanding>103.140000000016</TimeToLanding>
   <TimeToEject>2.33999999999999</TimeToEject>
   <MinLaunchGuideLen>0.601784913131885</MinLaunchGuideLen>
   <MaxVertVelocity>160.101413143608</MaxVertVelocity>
   <MaxHorzVelocity>0.</MaxHorzVelocity>
   <MaxVertAcceleration>97.1432437541713</MaxVertAcceleration>
   <MaxHorzAcceleration>0.</MaxHorzAcceleration>
   <MaxRange>0.</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>90.0000016695222</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>20.5555555555556</LaunchTemperature>
   <LaunchAltitude>853.44</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[I170-0   ] </SimulationName>
   <VelocityAtLaunchGuideEnd>18.3149063032675</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.24</TimeToFreeFlight>
   <TimeToMaxVelocity>1.94</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.78</TimeToMaxAcceleration>
   <SamplesPerSecond>100</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>0.804105834827939</ExecutionTime>
   <RangeAtLanding>0.</RangeAtLanding>
   <VelocityAtLanding>8.68102542774585</VelocityAtLanding>
   <XVelcoityAtLanding>0.</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.68102542774585</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,12.0799999999998</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>800.151589052873</DeployedAt_Altitude>
     <DeployedAt_Velocity>1.26482605845594e-002</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>12.0799999999998</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>I170</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>CSR</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>0.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>487.982889415089</MaxAltitude>
   <MaxVelocity>106.218493663217</MaxVelocity>
   <MaxAcceleration>64.6939391051648</MaxAcceleration>
   <TimeToApogee>10.1599999999998</TimeToApogee>
   <OptimalDelay>7.82999999999983</OptimalDelay>
   <MultiDelayCount>0</MultiDelayCount>
   <VelocityAtDeplyment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>0.,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>1</FinalState>
   <TimeToBurnout>2.32999999999999</TimeToBurnout>
   <TimeToLanding>66.8499999999973</TimeToLanding>
   <TimeToEject>2.32999999999999</TimeToEject>
   <MinLaunchGuideLen>0.841013244206615</MinLaunchGuideLen>
   <MaxVertVelocity>106.218493663217</MaxVertVelocity>
   <MaxHorzVelocity>0.</MaxHorzVelocity>
   <MaxVertAcceleration>64.6939391051648</MaxVertAcceleration>
   <MaxHorzAcceleration>0.</MaxHorzAcceleration>
   <MaxRange>0.</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchGuideLen>914.4</LaunchGuideLen>
   <LaunchBarometer>759.812806</LaunchBarometer>
   <LaunchLatitude>90.0000016695222</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>20.5555555555556</LaunchTemperature>
   <LaunchAltitude>853.44</LaunchAltitude>
   <CompStateMask>0</CompStateMask>
   <LaunchWindPreset>4</LaunchWindPreset>
   <LaunchWindLowSpeed>3.57632</LaunchWindLowSpeed>
   <LaunchWindHighSpeed>6.660896</LaunchWindHighSpeed>
   <LaunchWindTurbulencePreset>2</LaunchWindTurbulencePreset>
   <LaunchWindFrequency>1.e-002</LaunchWindFrequency>
   <LaunchWindDeltaFrequency>2.e-002</LaunchWindDeltaFrequency>
   <LaunchUseRandomConditions>0</LaunchUseRandomConditions>
   <LaunchCloudCoverPreset>6</LaunchCloudCoverPreset>
   <LaunchCCLow>1.</LaunchCCLow>
   <LaunchCCHigh>1.</LaunchCCHigh>
   <LaunchThermalPosPreset>1</LaunchThermalPosPreset>
   <LaunchThermalPos>0.</LaunchThermalPos>
   <LaunchMultipleThermals>0</LaunchMultipleThermals>
   <LaunchMaxThermals>3</LaunchMaxThermals>
   <LaunchThermalDia>300.</LaunchThermalDia>
   <LaunchThermalHeight>2000.</LaunchThermalHeight>
   <LaunchThermalSpeedPreset>1</LaunchThermalSpeedPreset>
   <LaunchThermalSpeed>6.</LaunchThermalSpeed>
   <LaunchLossPreset>2</LaunchLossPreset>
   <LaunchLossPercent>0.99</LaunchLossPercent>
   <LaunchSiteDia>2000.</LaunchSiteDia>
   <LaunchDriftRangeToLoss>1500.</LaunchDriftRangeToLoss>
   <LaunchPayloadDamagePreset>2</LaunchPayloadDamagePreset>
   <LaunchPayloadDamagePercent>0.98</LaunchPayloadDamagePercent>
   <LaunchEngineMisfirePreset>1</LaunchEngineMisfirePreset>
   <LaunchEngineMisfirePercent>0.</LaunchEngineMisfirePercent>
   <LaunchVariableIgnitionDelay>0</LaunchVariableIgnitionDelay>
   <LaunchVariableIgnitionDelaySec>8.e-002</LaunchVariableIgnitionDelaySec>
   <LaunchRecDeviceFailurePreset>1</LaunchRecDeviceFailurePreset>
   <LaunchRecDeviceFailurePercent>0.</LaunchRecDeviceFailurePercent>
   <LaunchAriframeFailurePreset>1</LaunchAriframeFailurePreset>
   <LaunchAirframeFailurePercent>0.</LaunchAirframeFailurePercent>
   <LaunchTrackLossPreset>1</LaunchTrackLossPreset>
   <LaunchTeckLossPercent>0.</LaunchTeckLossPercent>
   <SimulationName>[H110-*] </SimulationName>
   <VelocityAtLaunchGuideEnd>14.4601236997113</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>1.82880001810512</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.31</TimeToFreeFlight>
   <TimeToMaxVelocity>2.</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.950000000000001</TimeToMaxAcceleration>
   <SamplesPerSecond>100</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>Earth</LocationDatabaseDisplayName>
   <ExecutionTime>0.504142711074607</ExecutionTime>
   <RangeAtLanding>0.</RangeAtLanding>
   <VelocityAtLanding>8.60075972996016</VelocityAtLanding>
   <XVelcoityAtLanding>0.</XVelcoityAtLanding>
   <YVelocityAtLanding>-8.60075972996016</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,10.1599999999998</TimeToDeployment>
   <DeploymentType>32,32,80</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
    <SimulationEvent>
     <PartSerialNo>11</PartSerialNo>
     <Type>4</Type>
     <DeployAltitude>0.</DeployAltitude>
     <DeplyTime>0.</DeplyTime>
     <HasDeployed>1</HasDeployed>
     <DeployedAt_Altitude>487.982212259604</DeployedAt_Altitude>
     <DeployedAt_Velocity>6.77155484812493e-002</DeployedAt_Velocity>
     <DeployedAt_Range>0.</DeployedAt_Range>
     <DeployedAt_Time>10.1599999999998</DeployedAt_Time>
     <DeviceID>7</DeviceID>
    </SimulationEvent>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>H110</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg>CSR</EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>3</MountSerialNo>
     <EjectionDelay>-1.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
 </SimulationResultsList>
</RockSimDocument>
