<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Mystic Buzz</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>15</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>1085.6582555879424</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>141.748</KnownMass>
                    <Density>946.0</Density>
                    <Material>Polypropylene, bulk</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>209.55</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>184.23249586923845</CalcMass>
                    <CalcCG>209.55</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>323.84999999999997</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.524</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>101.6</BaseDia>
                    <ShoulderLen>95.25</ShoulderLen>
                    <ShoulderOD>98.55199999999999</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>193.81393222546183</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>215.89999999999998</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>193.81393222546183</CalcMass>
                    <CalcCG>215.89999999999998</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>431.79999999999995</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>1</SerialNo>
                    <OD>101.6</OD>
                    <ID>99.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>36.8544</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>330.2</Xb>
                            <CalcMass>62.47071852699882</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>203.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <OD>99.06</OD>
                            <ID>97.282</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>34.21875452546856</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>3.175</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>847.09</Xb>
                            <CalcMass>34.21875452546856</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>97.282</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>7.08738</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord mount</Name>
                            <KnownCG>842.01</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>842.01</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.399999999999945</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>387.62786445092365</KnownMass>
                    <Density>1121.29</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>431.8</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>387.62786445092365</CalcMass>
                    <CalcCG>431.8</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>863.6</Len>
                    <FinishCode>0</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>101.6</OD>
                    <ID>99.06</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>99.06</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>129.5364002722085</KnownMass>
                            <Density>1121.29</Density>
                            <Material>Paper</Material>
                            <Name>Body tube</Name>
                            <KnownCG>215.9</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>431.8</Xb>
                            <CalcMass>129.5364002722085</CalcMass>
                            <CalcCG>215.9</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>431.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>57.404</OD>
                            <ID>54.356</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>54.356</MotorDia>
                            <EngineOverhang>0.50038</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <CustomFinSet>
                            <KnownMass>271.83251251972877</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Fin set</Name>
                            <KnownCG>74.43497827670393</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>682.625</Xb>
                            <CalcMass>271.83251251972877</CalcMass>
                            <CalcCG>74.43497827670393</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>5.969</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>165.1</TabLength>
                            <TabDepth>22.098</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>165.10000000000002,0.0|123.825,119.685|0.0,119.685|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <CustomFinSet>
                            <KnownMass>239.1140849947033</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Fin set</Name>
                            <KnownCG>124.54098346189043</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>448.945</Xb>
                            <CalcMass>239.1140849947033</CalcMass>
                            <CalcCG>124.54098346189043</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>0.0</RootChord>
                            <TipChord>0.0</TipChord>
                            <SemiSpan>0.0</SemiSpan>
                            <SweepDistance>0.0</SweepDistance>
                            <Thickness>5.969</Thickness>
                            <ShapeCode>2</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>200.66</TabLength>
                            <TabDepth>22.098</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                            <PointList>200.66,0.0|200.66,119.685|167.64,119.685|0.0,0.0|</PointList>
                        </CustomFinSet>
                        <Ring>
                            <KnownMass>22.152312237114447</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>2.9845</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>847.725</Xb>
                            <CalcMass>22.152312237114447</CalcMass>
                            <CalcCG>2.9845</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.969</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>99.06</OD>
                            <ID>57.404</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>22.152312237114447</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>2.9845</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>673.735</Xb>
                            <CalcMass>22.152312237114447</CalcMass>
                            <CalcCG>2.9845</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.969</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>99.06</OD>
                            <ID>57.404</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>22.152312237114447</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>2.9845</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>650.875</Xb>
                            <CalcMass>22.152312237114447</CalcMass>
                            <CalcCG>2.9845</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.969</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>99.06</OD>
                            <ID>57.404</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>22.152312237114447</KnownMass>
                            <Density>724.996</Density>
                            <Material>Aircraft plywood (LOC)</Material>
                            <Name>Centering ring</Name>
                            <KnownCG>2.9845</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>441.325</Xb>
                            <CalcMass>22.152312237114447</CalcMass>
                            <CalcCG>2.9845</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.969</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>99.06</OD>
                            <ID>57.404</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>7.08738</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord mount</Name>
                            <KnownCG>431.79999999999995</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>431.79999999999995</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.399999999999945</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>102.058</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>330.2</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>330.2</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>60.96</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>170.001</KnownMass>
                            <Density>8.702750691294812E-8</Density>
                            <Material>Rip stop nylon</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>160.01999999999998</Xb>
                            <CalcMass>22.033102437216</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>152.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <Dia>1270.0</Dia>
                            <ShroudLineCount>16</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>1350.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.00102</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/16 In. braided nylon</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>