<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Public Missiles Ltd. Miranda</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>12</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>940.4753771508499</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>158.757</KnownMass>
                    <Density>1246.560093693538</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>228.6</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>216.45444806430123</CalcMass>
                    <CalcCG>228.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>336.54999999999995</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.3622</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>79.40039999999999</BaseDia>
                    <ShoulderLen>63.5</ShoulderLen>
                    <ShoulderOD>76.2508</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>123.20227260345506</KnownMass>
                    <Density>1050.0</Density>
                    <Material>Quantum tubing</Material>
                    <Name>Payload section</Name>
                    <KnownCG>152.4</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>123.20227260345506</CalcMass>
                    <CalcCG>152.4</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>304.8</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <OD>79.4</OD>
                    <ID>76.251</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>76.251</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>44.98836354608893</KnownMass>
                            <Density>958.70501055</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>63.5</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>241.3</Xb>
                            <CalcMass>44.98836354608893</CalcMass>
                            <CalcCG>63.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>127.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <OD>76.251</OD>
                            <ID>73.101</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>14.175</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>SCM-3</Name>
                            <KnownCG>704.85</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>704.85</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>18.6527122915968</KnownMass>
                            <Density>680.7846775</Density>
                            <Material>Birch</Material>
                            <Name>Bulkhead</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>698.85</Xb>
                            <CalcMass>18.6527122915968</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>1</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>76.251</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>377.70500403128153</KnownMass>
                    <Density>1072.8</Density>
                    <Material>PML Quantum polymer</Material>
                    <Name>Airframe</Name>
                    <KnownCG>457.2</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>377.70500403128153</CalcMass>
                    <CalcCG>457.2</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>914.4</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>79.40039999999999</OD>
                    <ID>76.2508</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>76.2508</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>81.2836240286235</KnownMass>
                            <Density>958.70501055</Density>
                            <Material>Kraft phenolic</Material>
                            <Name>54mm MMT</Name>
                            <KnownCG>152.39999999999998</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>81.2836240286235</CalcMass>
                            <CalcCG>152.39999999999998</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>304.79999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>57.81</OD>
                            <ID>54.661</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>54.661</MotorDia>
                            <EngineOverhang>12.7</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <FinSet>
                            <KnownMass>97.36338732607288</KnownMass>
                            <Density>1905.23598922</Density>
                            <Material>G10 fiberglass</Material>
                            <Name>Fin set</Name>
                            <KnownCG>56.19057376040285</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>803.275</Xb>
                            <CalcMass>97.36338732607288</CalcMass>
                            <CalcCG>56.19057376040285</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>7</SerialNo>
                            <FinCount>6</FinCount>
                            <RootChord>101.6</RootChord>
                            <TipChord>38.1</TipChord>
                            <SemiSpan>76.2</SemiSpan>
                            <SweepDistance>44.4563524352352</SweepDistance>
                            <Thickness>1.6002</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <Parachute>
                            <KnownMass>70.68321139242003</KnownMass>
                            <Density>0.00589</Density>
                            <Material>Nylon fabric, ripstop, 1.9 oz actual</Material>
                            <Name>Parachute, 36 in., 1.9oz nylon, 10 lines, spill hole</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>508.0</Xb>
                            <CalcMass>70.68321139242003</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>35.730000000000004</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <Dia>914.4</Dia>
                            <ShroudLineCount>10</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>914.4</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0035</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon Paracord, 275 lb, 2.38 mm dia.</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>6.721799774146877</KnownMass>
                            <Density>724.99563538</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>2.3875</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>908.05</Xb>
                            <CalcMass>6.721799774146877</CalcMass>
                            <CalcCG>2.3875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>4.775</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>76.251</OD>
                            <ID>57.81</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>8.446240553901834</KnownMass>
                            <Density>724.99563538</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>635.0</Xb>
                            <CalcMass>8.446240553901834</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>76.251</OD>
                            <ID>57.81</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>8.446240553901834</KnownMass>
                            <Density>724.99563538</Density>
                            <Material>Aircraft plywood (Birch)</Material>
                            <Name>Ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>800.0999999999999</Xb>
                            <CalcMass>8.446240553901834</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>76.251</OD>
                            <ID>57.81</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>43.50001968</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>558.8</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>558.8</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>33.02</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>